// Code generated by ent, DO NOT EDIT.

package userquotagrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldUserID, v))
}

// AmountUsd applies equality check predicate on the "amount_usd" field. It's identical to AmountUsdEQ.
func AmountUsd(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldAmountUsd, v))
}

// UsedAmountUsd applies equality check predicate on the "used_amount_usd" field. It's identical to UsedAmountUsdEQ.
func UsedAmountUsd(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldUsedAmountUsd, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldSource, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldSourceID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountUsdEQ applies the EQ predicate on the "amount_usd" field.
func AmountUsdEQ(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldAmountUsd, v))
}

// AmountUsdNEQ applies the NEQ predicate on the "amount_usd" field.
func AmountUsdNEQ(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldAmountUsd, v))
}

// AmountUsdIn applies the In predicate on the "amount_usd" field.
func AmountUsdIn(vs ...float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldAmountUsd, vs...))
}

// AmountUsdNotIn applies the NotIn predicate on the "amount_usd" field.
func AmountUsdNotIn(vs ...float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldAmountUsd, vs...))
}

// AmountUsdGT applies the GT predicate on the "amount_usd" field.
func AmountUsdGT(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldAmountUsd, v))
}

// AmountUsdGTE applies the GTE predicate on the "amount_usd" field.
func AmountUsdGTE(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldAmountUsd, v))
}

// AmountUsdLT applies the LT predicate on the "amount_usd" field.
func AmountUsdLT(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldAmountUsd, v))
}

// AmountUsdLTE applies the LTE predicate on the "amount_usd" field.
func AmountUsdLTE(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldAmountUsd, v))
}

// UsedAmountUsdEQ applies the EQ predicate on the "used_amount_usd" field.
func UsedAmountUsdEQ(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldUsedAmountUsd, v))
}

// UsedAmountUsdNEQ applies the NEQ predicate on the "used_amount_usd" field.
func UsedAmountUsdNEQ(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldUsedAmountUsd, v))
}

// UsedAmountUsdIn applies the In predicate on the "used_amount_usd" field.
func UsedAmountUsdIn(vs ...float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldUsedAmountUsd, vs...))
}

// UsedAmountUsdNotIn applies the NotIn predicate on the "used_amount_usd" field.
func UsedAmountUsdNotIn(vs ...float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldUsedAmountUsd, vs...))
}

// UsedAmountUsdGT applies the GT predicate on the "used_amount_usd" field.
func UsedAmountUsdGT(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldUsedAmountUsd, v))
}

// UsedAmountUsdGTE applies the GTE predicate on the "used_amount_usd" field.
func UsedAmountUsdGTE(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldUsedAmountUsd, v))
}

// UsedAmountUsdLT applies the LT predicate on the "used_amount_usd" field.
func UsedAmountUsdLT(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldUsedAmountUsd, v))
}

// UsedAmountUsdLTE applies the LTE predicate on the "used_amount_usd" field.
func UsedAmountUsdLTE(v float64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldUsedAmountUsd, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldExpiresAt, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContainsFold(FieldSource, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContainsFold(FieldSourceID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContainsFold(FieldStatus, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserQuotaGrant) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserQuotaGrant) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserQuotaGrant) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.NotPredicates(p))
}
