// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycampaign"
	"github.com/Wei-Shaw/sub2api/ent/lotterychance"
	"github.com/Wei-Shaw/sub2api/ent/lotterydraw"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// LotteryChanceCreate is the builder for creating a LotteryChance entity.
type LotteryChanceCreate struct {
	config
	mutation *LotteryChanceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCampaignID sets the "campaign_id" field.
func (_c *LotteryChanceCreate) SetCampaignID(v int64) *LotteryChanceCreate {
	_c.mutation.SetCampaignID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *LotteryChanceCreate) SetUserID(v int64) *LotteryChanceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *LotteryChanceCreate) SetSource(v string) *LotteryChanceCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableSource(v *string) *LotteryChanceCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *LotteryChanceCreate) SetSourceID(v string) *LotteryChanceCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableSourceID(v *string) *LotteryChanceCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *LotteryChanceCreate) SetStatus(v string) *LotteryChanceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableStatus(v *string) *LotteryChanceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *LotteryChanceCreate) SetExpiresAt(v time.Time) *LotteryChanceCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *LotteryChanceCreate) SetUsedAt(v time.Time) *LotteryChanceCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableUsedAt(v *time.Time) *LotteryChanceCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *LotteryChanceCreate) SetMetadata(v map[string]interface{}) *LotteryChanceCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryChanceCreate) SetCreatedAt(v time.Time) *LotteryChanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableCreatedAt(v *time.Time) *LotteryChanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryChanceCreate) SetUpdatedAt(v time.Time) *LotteryChanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableUpdatedAt(v *time.Time) *LotteryChanceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCampaign sets the "campaign" edge to the LotteryCampaign entity.
func (_c *LotteryChanceCreate) SetCampaign(v *LotteryCampaign) *LotteryChanceCreate {
	return _c.SetCampaignID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *LotteryChanceCreate) SetUser(v *User) *LotteryChanceCreate {
	return _c.SetUserID(v.ID)
}

// SetDrawID sets the "draw" edge to the LotteryDraw entity by ID.
func (_c *LotteryChanceCreate) SetDrawID(id int64) *LotteryChanceCreate {
	_c.mutation.SetDrawID(id)
	return _c
}

// SetNillableDrawID sets the "draw" edge to the LotteryDraw entity by ID if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableDrawID(id *int64) *LotteryChanceCreate {
	if id != nil {
		_c = _c.SetDrawID(*id)
	}
	return _c
}

// SetDraw sets the "draw" edge to the LotteryDraw entity.
func (_c *LotteryChanceCreate) SetDraw(v *LotteryDraw) *LotteryChanceCreate {
	return _c.SetDrawID(v.ID)
}

// Mutation returns the LotteryChanceMutation object of the builder.
func (_c *LotteryChanceCreate) Mutation() *LotteryChanceMutation {
	return _c.mutation
}

// Save creates the LotteryChance in the database.
func (_c *LotteryChanceCreate) Save(ctx context.Context) (*LotteryChance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryChanceCreate) SaveX(ctx context.Context) *LotteryChance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryChanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryChanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryChanceCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := lotterychance.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		v := lotterychance.DefaultSourceID
		_c.mutation.SetSourceID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := lotterychance.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotterychance.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotterychance.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryChanceCreate) check() error {
	if _, ok := _c.mutation.CampaignID(); !ok {
		return &ValidationError{Name: "campaign_id", err: errors.New(`ent: missing required field "LotteryChance.campaign_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LotteryChance.user_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "LotteryChance.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := lotterychance.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "LotteryChance.source_id"`)}
	}
	if v, ok := _c.mutation.SourceID(); ok {
		if err := lotterychance.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.source_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LotteryChance.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := lotterychance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "LotteryChance.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryChance.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotteryChance.updated_at"`)}
	}
	if len(_c.mutation.CampaignIDs()) == 0 {
		return &ValidationError{Name: "campaign", err: errors.New(`ent: missing required edge "LotteryChance.campaign"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "LotteryChance.user"`)}
	}
	return nil
}

func (_c *LotteryChanceCreate) sqlSave(ctx context.Context) (*LotteryChance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryChanceCreate) createSpec() (*LotteryChance, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryChance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterychance.Table, sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(lotterychance.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(lotterychance.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(lotterychance.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(lotterychance.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(lotterychance.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(lotterychance.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterychance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterychance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterychance.CampaignTable,
			Columns: []string{lotterychance.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CampaignID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterychance.UserTable,
			Columns: []string{lotterychance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DrawIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   lotterychance.DrawTable,
			Columns: []string{lotterychance.DrawColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryChance.Create().
//		SetCampaignID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryChanceUpsert) {
//			SetCampaignID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryChanceCreate) OnConflict(opts ...sql.ConflictOption) *LotteryChanceUpsertOne {
	_c.conflict = opts
	return &LotteryChanceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryChanceCreate) OnConflictColumns(columns ...string) *LotteryChanceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryChanceUpsertOne{
		create: _c,
	}
}

type (
	// LotteryChanceUpsertOne is the builder for "upsert"-ing
	//  one LotteryChance node.
	LotteryChanceUpsertOne struct {
		create *LotteryChanceCreate
	}

	// LotteryChanceUpsert is the "OnConflict" setter.
	LotteryChanceUpsert struct {
		*sql.UpdateSet
	}
)

// SetCampaignID sets the "campaign_id" field.
func (u *LotteryChanceUpsert) SetCampaignID(v int64) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldCampaignID, v)
	return u
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateCampaignID() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldCampaignID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryChanceUpsert) SetUserID(v int64) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateUserID() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldUserID)
	return u
}

// SetSource sets the "source" field.
func (u *LotteryChanceUpsert) SetSource(v string) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateSource() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldSource)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *LotteryChanceUpsert) SetSourceID(v string) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateSourceID() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldSourceID)
	return u
}

// SetStatus sets the "status" field.
func (u *LotteryChanceUpsert) SetStatus(v string) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateStatus() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *LotteryChanceUpsert) SetExpiresAt(v time.Time) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateExpiresAt() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldExpiresAt)
	return u
}

// SetUsedAt sets the "used_at" field.
func (u *LotteryChanceUpsert) SetUsedAt(v time.Time) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldUsedAt, v)
	return u
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateUsedAt() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldUsedAt)
	return u
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *LotteryChanceUpsert) ClearUsedAt() *LotteryChanceUpsert {
	u.SetNull(lotterychance.FieldUsedAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *LotteryChanceUpsert) SetMetadata(v map[string]interface{}) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateMetadata() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LotteryChanceUpsert) ClearMetadata() *LotteryChanceUpsert {
	u.SetNull(lotterychance.FieldMetadata)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryChanceUpsert) SetUpdatedAt(v time.Time) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateUpdatedAt() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryChanceUpsertOne) UpdateNewValues() *LotteryChanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotterychance.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryChanceUpsertOne) Ignore() *LotteryChanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryChanceUpsertOne) DoNothing() *LotteryChanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryChanceCreate.OnConflict
// documentation for more info.
func (u *LotteryChanceUpsertOne) Update(set func(*LotteryChanceUpsert)) *LotteryChanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryChanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetCampaignID sets the "campaign_id" field.
func (u *LotteryChanceUpsertOne) SetCampaignID(v int64) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateCampaignID() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateCampaignID()
	})
}

// SetUserID sets the "user_id" field.
func (u *LotteryChanceUpsertOne) SetUserID(v int64) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateUserID() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateUserID()
	})
}

// SetSource sets the "source" field.
func (u *LotteryChanceUpsertOne) SetSource(v string) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateSource() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateSource()
	})
}

// SetSourceID sets the "source_id" field.
func (u *LotteryChanceUpsertOne) SetSourceID(v string) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateSourceID() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateSourceID()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryChanceUpsertOne) SetStatus(v string) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateStatus() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *LotteryChanceUpsertOne) SetExpiresAt(v time.Time) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateExpiresAt() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *LotteryChanceUpsertOne) SetUsedAt(v time.Time) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateUsedAt() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *LotteryChanceUpsertOne) ClearUsedAt() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.ClearUsedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *LotteryChanceUpsertOne) SetMetadata(v map[string]interface{}) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateMetadata() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LotteryChanceUpsertOne) ClearMetadata() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.ClearMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryChanceUpsertOne) SetUpdatedAt(v time.Time) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateUpdatedAt() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryChanceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryChanceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryChanceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryChanceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryChanceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryChanceCreateBulk is the builder for creating many LotteryChance entities in bulk.
type LotteryChanceCreateBulk struct {
	config
	err      error
	builders []*LotteryChanceCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryChance entities in the database.
func (_c *LotteryChanceCreateBulk) Save(ctx context.Context) ([]*LotteryChance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryChance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryChanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryChanceCreateBulk) SaveX(ctx context.Context) []*LotteryChance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryChanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryChanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryChance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryChanceUpsert) {
//			SetCampaignID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryChanceCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryChanceUpsertBulk {
	_c.conflict = opts
	return &LotteryChanceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryChanceCreateBulk) OnConflictColumns(columns ...string) *LotteryChanceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryChanceUpsertBulk{
		create: _c,
	}
}

// LotteryChanceUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryChance nodes.
type LotteryChanceUpsertBulk struct {
	create *LotteryChanceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryChanceUpsertBulk) UpdateNewValues() *LotteryChanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotterychance.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryChanceUpsertBulk) Ignore() *LotteryChanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryChanceUpsertBulk) DoNothing() *LotteryChanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryChanceCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryChanceUpsertBulk) Update(set func(*LotteryChanceUpsert)) *LotteryChanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryChanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetCampaignID sets the "campaign_id" field.
func (u *LotteryChanceUpsertBulk) SetCampaignID(v int64) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateCampaignID() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateCampaignID()
	})
}

// SetUserID sets the "user_id" field.
func (u *LotteryChanceUpsertBulk) SetUserID(v int64) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateUserID() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateUserID()
	})
}

// SetSource sets the "source" field.
func (u *LotteryChanceUpsertBulk) SetSource(v string) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateSource() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateSource()
	})
}

// SetSourceID sets the "source_id" field.
func (u *LotteryChanceUpsertBulk) SetSourceID(v string) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateSourceID() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateSourceID()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryChanceUpsertBulk) SetStatus(v string) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateStatus() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *LotteryChanceUpsertBulk) SetExpiresAt(v time.Time) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateExpiresAt() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *LotteryChanceUpsertBulk) SetUsedAt(v time.Time) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateUsedAt() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *LotteryChanceUpsertBulk) ClearUsedAt() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.ClearUsedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *LotteryChanceUpsertBulk) SetMetadata(v map[string]interface{}) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateMetadata() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LotteryChanceUpsertBulk) ClearMetadata() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.ClearMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryChanceUpsertBulk) SetUpdatedAt(v time.Time) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateUpdatedAt() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryChanceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryChanceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryChanceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryChanceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
