// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycampaign"
	"github.com/Wei-Shaw/sub2api/ent/lotterydraw"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryPrizeUpdate is the builder for updating LotteryPrize entities.
type LotteryPrizeUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryPrizeMutation
}

// Where appends a list predicates to the LotteryPrizeUpdate builder.
func (_u *LotteryPrizeUpdate) Where(ps ...predicate.LotteryPrize) *LotteryPrizeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *LotteryPrizeUpdate) SetCampaignID(v int64) *LotteryPrizeUpdate {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableCampaignID(v *int64) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LotteryPrizeUpdate) SetName(v string) *LotteryPrizeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableName(v *string) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *LotteryPrizeUpdate) SetDescription(v string) *LotteryPrizeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableDescription(v *string) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LotteryPrizeUpdate) SetStatus(v string) *LotteryPrizeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableStatus(v *string) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *LotteryPrizeUpdate) SetWeight(v int) *LotteryPrizeUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableWeight(v *int) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *LotteryPrizeUpdate) AddWeight(v int) *LotteryPrizeUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetStockTotal sets the "stock_total" field.
func (_u *LotteryPrizeUpdate) SetStockTotal(v int) *LotteryPrizeUpdate {
	_u.mutation.ResetStockTotal()
	_u.mutation.SetStockTotal(v)
	return _u
}

// SetNillableStockTotal sets the "stock_total" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableStockTotal(v *int) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetStockTotal(*v)
	}
	return _u
}

// AddStockTotal adds value to the "stock_total" field.
func (_u *LotteryPrizeUpdate) AddStockTotal(v int) *LotteryPrizeUpdate {
	_u.mutation.AddStockTotal(v)
	return _u
}

// SetStockUsed sets the "stock_used" field.
func (_u *LotteryPrizeUpdate) SetStockUsed(v int) *LotteryPrizeUpdate {
	_u.mutation.ResetStockUsed()
	_u.mutation.SetStockUsed(v)
	return _u
}

// SetNillableStockUsed sets the "stock_used" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableStockUsed(v *int) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetStockUsed(*v)
	}
	return _u
}

// AddStockUsed adds value to the "stock_used" field.
func (_u *LotteryPrizeUpdate) AddStockUsed(v int) *LotteryPrizeUpdate {
	_u.mutation.AddStockUsed(v)
	return _u
}

// SetRedeemType sets the "redeem_type" field.
func (_u *LotteryPrizeUpdate) SetRedeemType(v string) *LotteryPrizeUpdate {
	_u.mutation.SetRedeemType(v)
	return _u
}

// SetNillableRedeemType sets the "redeem_type" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableRedeemType(v *string) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetRedeemType(*v)
	}
	return _u
}

// SetRedeemValue sets the "redeem_value" field.
func (_u *LotteryPrizeUpdate) SetRedeemValue(v float64) *LotteryPrizeUpdate {
	_u.mutation.ResetRedeemValue()
	_u.mutation.SetRedeemValue(v)
	return _u
}

// SetNillableRedeemValue sets the "redeem_value" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableRedeemValue(v *float64) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetRedeemValue(*v)
	}
	return _u
}

// AddRedeemValue adds value to the "redeem_value" field.
func (_u *LotteryPrizeUpdate) AddRedeemValue(v float64) *LotteryPrizeUpdate {
	_u.mutation.AddRedeemValue(v)
	return _u
}

// SetRedeemGroupID sets the "redeem_group_id" field.
func (_u *LotteryPrizeUpdate) SetRedeemGroupID(v int64) *LotteryPrizeUpdate {
	_u.mutation.ResetRedeemGroupID()
	_u.mutation.SetRedeemGroupID(v)
	return _u
}

// SetNillableRedeemGroupID sets the "redeem_group_id" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableRedeemGroupID(v *int64) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetRedeemGroupID(*v)
	}
	return _u
}

// AddRedeemGroupID adds value to the "redeem_group_id" field.
func (_u *LotteryPrizeUpdate) AddRedeemGroupID(v int64) *LotteryPrizeUpdate {
	_u.mutation.AddRedeemGroupID(v)
	return _u
}

// ClearRedeemGroupID clears the value of the "redeem_group_id" field.
func (_u *LotteryPrizeUpdate) ClearRedeemGroupID() *LotteryPrizeUpdate {
	_u.mutation.ClearRedeemGroupID()
	return _u
}

// SetRedeemValidityDays sets the "redeem_validity_days" field.
func (_u *LotteryPrizeUpdate) SetRedeemValidityDays(v int) *LotteryPrizeUpdate {
	_u.mutation.ResetRedeemValidityDays()
	_u.mutation.SetRedeemValidityDays(v)
	return _u
}

// SetNillableRedeemValidityDays sets the "redeem_validity_days" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableRedeemValidityDays(v *int) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetRedeemValidityDays(*v)
	}
	return _u
}

// AddRedeemValidityDays adds value to the "redeem_validity_days" field.
func (_u *LotteryPrizeUpdate) AddRedeemValidityDays(v int) *LotteryPrizeUpdate {
	_u.mutation.AddRedeemValidityDays(v)
	return _u
}

// SetRedeemMetadata sets the "redeem_metadata" field.
func (_u *LotteryPrizeUpdate) SetRedeemMetadata(v map[string]interface{}) *LotteryPrizeUpdate {
	_u.mutation.SetRedeemMetadata(v)
	return _u
}

// ClearRedeemMetadata clears the value of the "redeem_metadata" field.
func (_u *LotteryPrizeUpdate) ClearRedeemMetadata() *LotteryPrizeUpdate {
	_u.mutation.ClearRedeemMetadata()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LotteryPrizeUpdate) SetSortOrder(v int) *LotteryPrizeUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableSortOrder(v *int) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LotteryPrizeUpdate) AddSortOrder(v int) *LotteryPrizeUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *LotteryPrizeUpdate) SetMetadata(v map[string]interface{}) *LotteryPrizeUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *LotteryPrizeUpdate) ClearMetadata() *LotteryPrizeUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryPrizeUpdate) SetUpdatedAt(v time.Time) *LotteryPrizeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCampaign sets the "campaign" edge to the LotteryCampaign entity.
func (_u *LotteryPrizeUpdate) SetCampaign(v *LotteryCampaign) *LotteryPrizeUpdate {
	return _u.SetCampaignID(v.ID)
}

// AddDrawIDs adds the "draws" edge to the LotteryDraw entity by IDs.
func (_u *LotteryPrizeUpdate) AddDrawIDs(ids ...int64) *LotteryPrizeUpdate {
	_u.mutation.AddDrawIDs(ids...)
	return _u
}

// AddDraws adds the "draws" edges to the LotteryDraw entity.
func (_u *LotteryPrizeUpdate) AddDraws(v ...*LotteryDraw) *LotteryPrizeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDrawIDs(ids...)
}

// Mutation returns the LotteryPrizeMutation object of the builder.
func (_u *LotteryPrizeUpdate) Mutation() *LotteryPrizeMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the LotteryCampaign entity.
func (_u *LotteryPrizeUpdate) ClearCampaign() *LotteryPrizeUpdate {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearDraws clears all "draws" edges to the LotteryDraw entity.
func (_u *LotteryPrizeUpdate) ClearDraws() *LotteryPrizeUpdate {
	_u.mutation.ClearDraws()
	return _u
}

// RemoveDrawIDs removes the "draws" edge to LotteryDraw entities by IDs.
func (_u *LotteryPrizeUpdate) RemoveDrawIDs(ids ...int64) *LotteryPrizeUpdate {
	_u.mutation.RemoveDrawIDs(ids...)
	return _u
}

// RemoveDraws removes "draws" edges to LotteryDraw entities.
func (_u *LotteryPrizeUpdate) RemoveDraws(v ...*LotteryDraw) *LotteryPrizeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDrawIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryPrizeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryPrizeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryPrizeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryPrizeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryPrizeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryprize.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryPrizeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := lotteryprize.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := lotteryprize.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedeemType(); ok {
		if err := lotteryprize.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.redeem_type": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryPrize.campaign"`)
	}
	return nil
}

func (_u *LotteryPrizeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryprize.Table, lotteryprize.Columns, sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(lotteryprize.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(lotteryprize.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(lotteryprize.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(lotteryprize.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(lotteryprize.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StockTotal(); ok {
		_spec.SetField(lotteryprize.FieldStockTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStockTotal(); ok {
		_spec.AddField(lotteryprize.FieldStockTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StockUsed(); ok {
		_spec.SetField(lotteryprize.FieldStockUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStockUsed(); ok {
		_spec.AddField(lotteryprize.FieldStockUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RedeemType(); ok {
		_spec.SetField(lotteryprize.FieldRedeemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeemValue(); ok {
		_spec.SetField(lotteryprize.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRedeemValue(); ok {
		_spec.AddField(lotteryprize.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RedeemGroupID(); ok {
		_spec.SetField(lotteryprize.FieldRedeemGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemGroupID(); ok {
		_spec.AddField(lotteryprize.FieldRedeemGroupID, field.TypeInt64, value)
	}
	if _u.mutation.RedeemGroupIDCleared() {
		_spec.ClearField(lotteryprize.FieldRedeemGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RedeemValidityDays(); ok {
		_spec.SetField(lotteryprize.FieldRedeemValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRedeemValidityDays(); ok {
		_spec.AddField(lotteryprize.FieldRedeemValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RedeemMetadata(); ok {
		_spec.SetField(lotteryprize.FieldRedeemMetadata, field.TypeJSON, value)
	}
	if _u.mutation.RedeemMetadataCleared() {
		_spec.ClearField(lotteryprize.FieldRedeemMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(lotteryprize.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(lotteryprize.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(lotteryprize.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(lotteryprize.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryprize.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryprize.CampaignTable,
			Columns: []string{lotteryprize.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryprize.CampaignTable,
			Columns: []string{lotteryprize.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DrawsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryprize.DrawsTable,
			Columns: []string{lotteryprize.DrawsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDrawsIDs(); len(nodes) > 0 && !_u.mutation.DrawsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryprize.DrawsTable,
			Columns: []string{lotteryprize.DrawsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DrawsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryprize.DrawsTable,
			Columns: []string{lotteryprize.DrawsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryprize.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryPrizeUpdateOne is the builder for updating a single LotteryPrize entity.
type LotteryPrizeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryPrizeMutation
}

// SetCampaignID sets the "campaign_id" field.
func (_u *LotteryPrizeUpdateOne) SetCampaignID(v int64) *LotteryPrizeUpdateOne {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableCampaignID(v *int64) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LotteryPrizeUpdateOne) SetName(v string) *LotteryPrizeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableName(v *string) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *LotteryPrizeUpdateOne) SetDescription(v string) *LotteryPrizeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableDescription(v *string) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LotteryPrizeUpdateOne) SetStatus(v string) *LotteryPrizeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableStatus(v *string) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *LotteryPrizeUpdateOne) SetWeight(v int) *LotteryPrizeUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableWeight(v *int) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *LotteryPrizeUpdateOne) AddWeight(v int) *LotteryPrizeUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetStockTotal sets the "stock_total" field.
func (_u *LotteryPrizeUpdateOne) SetStockTotal(v int) *LotteryPrizeUpdateOne {
	_u.mutation.ResetStockTotal()
	_u.mutation.SetStockTotal(v)
	return _u
}

// SetNillableStockTotal sets the "stock_total" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableStockTotal(v *int) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetStockTotal(*v)
	}
	return _u
}

// AddStockTotal adds value to the "stock_total" field.
func (_u *LotteryPrizeUpdateOne) AddStockTotal(v int) *LotteryPrizeUpdateOne {
	_u.mutation.AddStockTotal(v)
	return _u
}

// SetStockUsed sets the "stock_used" field.
func (_u *LotteryPrizeUpdateOne) SetStockUsed(v int) *LotteryPrizeUpdateOne {
	_u.mutation.ResetStockUsed()
	_u.mutation.SetStockUsed(v)
	return _u
}

// SetNillableStockUsed sets the "stock_used" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableStockUsed(v *int) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetStockUsed(*v)
	}
	return _u
}

// AddStockUsed adds value to the "stock_used" field.
func (_u *LotteryPrizeUpdateOne) AddStockUsed(v int) *LotteryPrizeUpdateOne {
	_u.mutation.AddStockUsed(v)
	return _u
}

// SetRedeemType sets the "redeem_type" field.
func (_u *LotteryPrizeUpdateOne) SetRedeemType(v string) *LotteryPrizeUpdateOne {
	_u.mutation.SetRedeemType(v)
	return _u
}

// SetNillableRedeemType sets the "redeem_type" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableRedeemType(v *string) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetRedeemType(*v)
	}
	return _u
}

// SetRedeemValue sets the "redeem_value" field.
func (_u *LotteryPrizeUpdateOne) SetRedeemValue(v float64) *LotteryPrizeUpdateOne {
	_u.mutation.ResetRedeemValue()
	_u.mutation.SetRedeemValue(v)
	return _u
}

// SetNillableRedeemValue sets the "redeem_value" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableRedeemValue(v *float64) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetRedeemValue(*v)
	}
	return _u
}

// AddRedeemValue adds value to the "redeem_value" field.
func (_u *LotteryPrizeUpdateOne) AddRedeemValue(v float64) *LotteryPrizeUpdateOne {
	_u.mutation.AddRedeemValue(v)
	return _u
}

// SetRedeemGroupID sets the "redeem_group_id" field.
func (_u *LotteryPrizeUpdateOne) SetRedeemGroupID(v int64) *LotteryPrizeUpdateOne {
	_u.mutation.ResetRedeemGroupID()
	_u.mutation.SetRedeemGroupID(v)
	return _u
}

// SetNillableRedeemGroupID sets the "redeem_group_id" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableRedeemGroupID(v *int64) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetRedeemGroupID(*v)
	}
	return _u
}

// AddRedeemGroupID adds value to the "redeem_group_id" field.
func (_u *LotteryPrizeUpdateOne) AddRedeemGroupID(v int64) *LotteryPrizeUpdateOne {
	_u.mutation.AddRedeemGroupID(v)
	return _u
}

// ClearRedeemGroupID clears the value of the "redeem_group_id" field.
func (_u *LotteryPrizeUpdateOne) ClearRedeemGroupID() *LotteryPrizeUpdateOne {
	_u.mutation.ClearRedeemGroupID()
	return _u
}

// SetRedeemValidityDays sets the "redeem_validity_days" field.
func (_u *LotteryPrizeUpdateOne) SetRedeemValidityDays(v int) *LotteryPrizeUpdateOne {
	_u.mutation.ResetRedeemValidityDays()
	_u.mutation.SetRedeemValidityDays(v)
	return _u
}

// SetNillableRedeemValidityDays sets the "redeem_validity_days" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableRedeemValidityDays(v *int) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetRedeemValidityDays(*v)
	}
	return _u
}

// AddRedeemValidityDays adds value to the "redeem_validity_days" field.
func (_u *LotteryPrizeUpdateOne) AddRedeemValidityDays(v int) *LotteryPrizeUpdateOne {
	_u.mutation.AddRedeemValidityDays(v)
	return _u
}

// SetRedeemMetadata sets the "redeem_metadata" field.
func (_u *LotteryPrizeUpdateOne) SetRedeemMetadata(v map[string]interface{}) *LotteryPrizeUpdateOne {
	_u.mutation.SetRedeemMetadata(v)
	return _u
}

// ClearRedeemMetadata clears the value of the "redeem_metadata" field.
func (_u *LotteryPrizeUpdateOne) ClearRedeemMetadata() *LotteryPrizeUpdateOne {
	_u.mutation.ClearRedeemMetadata()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LotteryPrizeUpdateOne) SetSortOrder(v int) *LotteryPrizeUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableSortOrder(v *int) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LotteryPrizeUpdateOne) AddSortOrder(v int) *LotteryPrizeUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *LotteryPrizeUpdateOne) SetMetadata(v map[string]interface{}) *LotteryPrizeUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *LotteryPrizeUpdateOne) ClearMetadata() *LotteryPrizeUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryPrizeUpdateOne) SetUpdatedAt(v time.Time) *LotteryPrizeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCampaign sets the "campaign" edge to the LotteryCampaign entity.
func (_u *LotteryPrizeUpdateOne) SetCampaign(v *LotteryCampaign) *LotteryPrizeUpdateOne {
	return _u.SetCampaignID(v.ID)
}

// AddDrawIDs adds the "draws" edge to the LotteryDraw entity by IDs.
func (_u *LotteryPrizeUpdateOne) AddDrawIDs(ids ...int64) *LotteryPrizeUpdateOne {
	_u.mutation.AddDrawIDs(ids...)
	return _u
}

// AddDraws adds the "draws" edges to the LotteryDraw entity.
func (_u *LotteryPrizeUpdateOne) AddDraws(v ...*LotteryDraw) *LotteryPrizeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDrawIDs(ids...)
}

// Mutation returns the LotteryPrizeMutation object of the builder.
func (_u *LotteryPrizeUpdateOne) Mutation() *LotteryPrizeMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the LotteryCampaign entity.
func (_u *LotteryPrizeUpdateOne) ClearCampaign() *LotteryPrizeUpdateOne {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearDraws clears all "draws" edges to the LotteryDraw entity.
func (_u *LotteryPrizeUpdateOne) ClearDraws() *LotteryPrizeUpdateOne {
	_u.mutation.ClearDraws()
	return _u
}

// RemoveDrawIDs removes the "draws" edge to LotteryDraw entities by IDs.
func (_u *LotteryPrizeUpdateOne) RemoveDrawIDs(ids ...int64) *LotteryPrizeUpdateOne {
	_u.mutation.RemoveDrawIDs(ids...)
	return _u
}

// RemoveDraws removes "draws" edges to LotteryDraw entities.
func (_u *LotteryPrizeUpdateOne) RemoveDraws(v ...*LotteryDraw) *LotteryPrizeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDrawIDs(ids...)
}

// Where appends a list predicates to the LotteryPrizeUpdate builder.
func (_u *LotteryPrizeUpdateOne) Where(ps ...predicate.LotteryPrize) *LotteryPrizeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryPrizeUpdateOne) Select(field string, fields ...string) *LotteryPrizeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryPrize entity.
func (_u *LotteryPrizeUpdateOne) Save(ctx context.Context) (*LotteryPrize, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryPrizeUpdateOne) SaveX(ctx context.Context) *LotteryPrize {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryPrizeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryPrizeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryPrizeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryprize.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryPrizeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := lotteryprize.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := lotteryprize.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedeemType(); ok {
		if err := lotteryprize.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.redeem_type": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryPrize.campaign"`)
	}
	return nil
}

func (_u *LotteryPrizeUpdateOne) sqlSave(ctx context.Context) (_node *LotteryPrize, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryprize.Table, lotteryprize.Columns, sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryPrize.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotteryprize.FieldID)
		for _, f := range fields {
			if !lotteryprize.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotteryprize.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(lotteryprize.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(lotteryprize.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(lotteryprize.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(lotteryprize.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(lotteryprize.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StockTotal(); ok {
		_spec.SetField(lotteryprize.FieldStockTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStockTotal(); ok {
		_spec.AddField(lotteryprize.FieldStockTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StockUsed(); ok {
		_spec.SetField(lotteryprize.FieldStockUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStockUsed(); ok {
		_spec.AddField(lotteryprize.FieldStockUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RedeemType(); ok {
		_spec.SetField(lotteryprize.FieldRedeemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeemValue(); ok {
		_spec.SetField(lotteryprize.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRedeemValue(); ok {
		_spec.AddField(lotteryprize.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RedeemGroupID(); ok {
		_spec.SetField(lotteryprize.FieldRedeemGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemGroupID(); ok {
		_spec.AddField(lotteryprize.FieldRedeemGroupID, field.TypeInt64, value)
	}
	if _u.mutation.RedeemGroupIDCleared() {
		_spec.ClearField(lotteryprize.FieldRedeemGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RedeemValidityDays(); ok {
		_spec.SetField(lotteryprize.FieldRedeemValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRedeemValidityDays(); ok {
		_spec.AddField(lotteryprize.FieldRedeemValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RedeemMetadata(); ok {
		_spec.SetField(lotteryprize.FieldRedeemMetadata, field.TypeJSON, value)
	}
	if _u.mutation.RedeemMetadataCleared() {
		_spec.ClearField(lotteryprize.FieldRedeemMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(lotteryprize.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(lotteryprize.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(lotteryprize.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(lotteryprize.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryprize.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryprize.CampaignTable,
			Columns: []string{lotteryprize.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryprize.CampaignTable,
			Columns: []string{lotteryprize.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DrawsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryprize.DrawsTable,
			Columns: []string{lotteryprize.DrawsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDrawsIDs(); len(nodes) > 0 && !_u.mutation.DrawsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryprize.DrawsTable,
			Columns: []string{lotteryprize.DrawsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DrawsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryprize.DrawsTable,
			Columns: []string{lotteryprize.DrawsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LotteryPrize{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryprize.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
