// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycampaign"
	"github.com/Wei-Shaw/sub2api/ent/lotterychance"
	"github.com/Wei-Shaw/sub2api/ent/lotterydraw"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
)

// LotteryCampaignCreate is the builder for creating a LotteryCampaign entity.
type LotteryCampaignCreate struct {
	config
	mutation *LotteryCampaignMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *LotteryCampaignCreate) SetName(v string) *LotteryCampaignCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *LotteryCampaignCreate) SetDescription(v string) *LotteryCampaignCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableDescription(v *string) *LotteryCampaignCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *LotteryCampaignCreate) SetStatus(v string) *LotteryCampaignCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableStatus(v *string) *LotteryCampaignCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *LotteryCampaignCreate) SetStartsAt(v time.Time) *LotteryCampaignCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableStartsAt(v *time.Time) *LotteryCampaignCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *LotteryCampaignCreate) SetEndsAt(v time.Time) *LotteryCampaignCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableEndsAt(v *time.Time) *LotteryCampaignCreate {
	if v != nil {
		_c.SetEndsAt(*v)
	}
	return _c
}

// SetChanceExpiresInDays sets the "chance_expires_in_days" field.
func (_c *LotteryCampaignCreate) SetChanceExpiresInDays(v int) *LotteryCampaignCreate {
	_c.mutation.SetChanceExpiresInDays(v)
	return _c
}

// SetNillableChanceExpiresInDays sets the "chance_expires_in_days" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableChanceExpiresInDays(v *int) *LotteryCampaignCreate {
	if v != nil {
		_c.SetChanceExpiresInDays(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *LotteryCampaignCreate) SetMetadata(v map[string]interface{}) *LotteryCampaignCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryCampaignCreate) SetCreatedAt(v time.Time) *LotteryCampaignCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableCreatedAt(v *time.Time) *LotteryCampaignCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryCampaignCreate) SetUpdatedAt(v time.Time) *LotteryCampaignCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableUpdatedAt(v *time.Time) *LotteryCampaignCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddPrizeIDs adds the "prizes" edge to the LotteryPrize entity by IDs.
func (_c *LotteryCampaignCreate) AddPrizeIDs(ids ...int64) *LotteryCampaignCreate {
	_c.mutation.AddPrizeIDs(ids...)
	return _c
}

// AddPrizes adds the "prizes" edges to the LotteryPrize entity.
func (_c *LotteryCampaignCreate) AddPrizes(v ...*LotteryPrize) *LotteryCampaignCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPrizeIDs(ids...)
}

// AddChanceIDs adds the "chances" edge to the LotteryChance entity by IDs.
func (_c *LotteryCampaignCreate) AddChanceIDs(ids ...int64) *LotteryCampaignCreate {
	_c.mutation.AddChanceIDs(ids...)
	return _c
}

// AddChances adds the "chances" edges to the LotteryChance entity.
func (_c *LotteryCampaignCreate) AddChances(v ...*LotteryChance) *LotteryCampaignCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChanceIDs(ids...)
}

// AddDrawIDs adds the "draws" edge to the LotteryDraw entity by IDs.
func (_c *LotteryCampaignCreate) AddDrawIDs(ids ...int64) *LotteryCampaignCreate {
	_c.mutation.AddDrawIDs(ids...)
	return _c
}

// AddDraws adds the "draws" edges to the LotteryDraw entity.
func (_c *LotteryCampaignCreate) AddDraws(v ...*LotteryDraw) *LotteryCampaignCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDrawIDs(ids...)
}

// Mutation returns the LotteryCampaignMutation object of the builder.
func (_c *LotteryCampaignCreate) Mutation() *LotteryCampaignMutation {
	return _c.mutation
}

// Save creates the LotteryCampaign in the database.
func (_c *LotteryCampaignCreate) Save(ctx context.Context) (*LotteryCampaign, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryCampaignCreate) SaveX(ctx context.Context) *LotteryCampaign {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryCampaignCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryCampaignCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryCampaignCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := lotterycampaign.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := lotterycampaign.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		v := lotterycampaign.DefaultStartsAt()
		_c.mutation.SetStartsAt(v)
	}
	if _, ok := _c.mutation.ChanceExpiresInDays(); !ok {
		v := lotterycampaign.DefaultChanceExpiresInDays
		_c.mutation.SetChanceExpiresInDays(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotterycampaign.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotterycampaign.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryCampaignCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "LotteryCampaign.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := lotterycampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "LotteryCampaign.description"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LotteryCampaign.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := lotterycampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "LotteryCampaign.starts_at"`)}
	}
	if _, ok := _c.mutation.ChanceExpiresInDays(); !ok {
		return &ValidationError{Name: "chance_expires_in_days", err: errors.New(`ent: missing required field "LotteryCampaign.chance_expires_in_days"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryCampaign.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotteryCampaign.updated_at"`)}
	}
	return nil
}

func (_c *LotteryCampaignCreate) sqlSave(ctx context.Context) (*LotteryCampaign, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryCampaignCreate) createSpec() (*LotteryCampaign, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryCampaign{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterycampaign.Table, sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(lotterycampaign.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(lotterycampaign.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(lotterycampaign.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(lotterycampaign.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(lotterycampaign.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = &value
	}
	if value, ok := _c.mutation.ChanceExpiresInDays(); ok {
		_spec.SetField(lotterycampaign.FieldChanceExpiresInDays, field.TypeInt, value)
		_node.ChanceExpiresInDays = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(lotterycampaign.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterycampaign.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterycampaign.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PrizesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotterycampaign.PrizesTable,
			Columns: []string{lotterycampaign.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotterycampaign.ChancesTable,
			Columns: []string{lotterycampaign.ChancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DrawsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotterycampaign.DrawsTable,
			Columns: []string{lotterycampaign.DrawsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryCampaign.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryCampaignUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryCampaignCreate) OnConflict(opts ...sql.ConflictOption) *LotteryCampaignUpsertOne {
	_c.conflict = opts
	return &LotteryCampaignUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryCampaignCreate) OnConflictColumns(columns ...string) *LotteryCampaignUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryCampaignUpsertOne{
		create: _c,
	}
}

type (
	// LotteryCampaignUpsertOne is the builder for "upsert"-ing
	//  one LotteryCampaign node.
	LotteryCampaignUpsertOne struct {
		create *LotteryCampaignCreate
	}

	// LotteryCampaignUpsert is the "OnConflict" setter.
	LotteryCampaignUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *LotteryCampaignUpsert) SetName(v string) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateName() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *LotteryCampaignUpsert) SetDescription(v string) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateDescription() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *LotteryCampaignUpsert) SetStatus(v string) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateStatus() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldStatus)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *LotteryCampaignUpsert) SetStartsAt(v time.Time) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateStartsAt() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldStartsAt)
	return u
}

// SetEndsAt sets the "ends_at" field.
func (u *LotteryCampaignUpsert) SetEndsAt(v time.Time) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldEndsAt, v)
	return u
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateEndsAt() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldEndsAt)
	return u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *LotteryCampaignUpsert) ClearEndsAt() *LotteryCampaignUpsert {
	u.SetNull(lotterycampaign.FieldEndsAt)
	return u
}

// SetChanceExpiresInDays sets the "chance_expires_in_days" field.
func (u *LotteryCampaignUpsert) SetChanceExpiresInDays(v int) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldChanceExpiresInDays, v)
	return u
}

// UpdateChanceExpiresInDays sets the "chance_expires_in_days" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateChanceExpiresInDays() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldChanceExpiresInDays)
	return u
}

// AddChanceExpiresInDays adds v to the "chance_expires_in_days" field.
func (u *LotteryCampaignUpsert) AddChanceExpiresInDays(v int) *LotteryCampaignUpsert {
	u.Add(lotterycampaign.FieldChanceExpiresInDays, v)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *LotteryCampaignUpsert) SetMetadata(v map[string]interface{}) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateMetadata() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LotteryCampaignUpsert) ClearMetadata() *LotteryCampaignUpsert {
	u.SetNull(lotterycampaign.FieldMetadata)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryCampaignUpsert) SetUpdatedAt(v time.Time) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateUpdatedAt() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryCampaignUpsertOne) UpdateNewValues() *LotteryCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotterycampaign.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryCampaignUpsertOne) Ignore() *LotteryCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryCampaignUpsertOne) DoNothing() *LotteryCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryCampaignCreate.OnConflict
// documentation for more info.
func (u *LotteryCampaignUpsertOne) Update(set func(*LotteryCampaignUpsert)) *LotteryCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryCampaignUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *LotteryCampaignUpsertOne) SetName(v string) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateName() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *LotteryCampaignUpsertOne) SetDescription(v string) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateDescription() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateDescription()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryCampaignUpsertOne) SetStatus(v string) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateStatus() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateStatus()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *LotteryCampaignUpsertOne) SetStartsAt(v time.Time) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateStartsAt() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *LotteryCampaignUpsertOne) SetEndsAt(v time.Time) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateEndsAt() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *LotteryCampaignUpsertOne) ClearEndsAt() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.ClearEndsAt()
	})
}

// SetChanceExpiresInDays sets the "chance_expires_in_days" field.
func (u *LotteryCampaignUpsertOne) SetChanceExpiresInDays(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetChanceExpiresInDays(v)
	})
}

// AddChanceExpiresInDays adds v to the "chance_expires_in_days" field.
func (u *LotteryCampaignUpsertOne) AddChanceExpiresInDays(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddChanceExpiresInDays(v)
	})
}

// UpdateChanceExpiresInDays sets the "chance_expires_in_days" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateChanceExpiresInDays() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateChanceExpiresInDays()
	})
}

// SetMetadata sets the "metadata" field.
func (u *LotteryCampaignUpsertOne) SetMetadata(v map[string]interface{}) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateMetadata() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LotteryCampaignUpsertOne) ClearMetadata() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.ClearMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryCampaignUpsertOne) SetUpdatedAt(v time.Time) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateUpdatedAt() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryCampaignUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryCampaignCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryCampaignUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryCampaignUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryCampaignUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryCampaignCreateBulk is the builder for creating many LotteryCampaign entities in bulk.
type LotteryCampaignCreateBulk struct {
	config
	err      error
	builders []*LotteryCampaignCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryCampaign entities in the database.
func (_c *LotteryCampaignCreateBulk) Save(ctx context.Context) ([]*LotteryCampaign, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryCampaign, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryCampaignMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryCampaignCreateBulk) SaveX(ctx context.Context) []*LotteryCampaign {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryCampaignCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryCampaignCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryCampaign.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryCampaignUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryCampaignCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryCampaignUpsertBulk {
	_c.conflict = opts
	return &LotteryCampaignUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryCampaignCreateBulk) OnConflictColumns(columns ...string) *LotteryCampaignUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryCampaignUpsertBulk{
		create: _c,
	}
}

// LotteryCampaignUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryCampaign nodes.
type LotteryCampaignUpsertBulk struct {
	create *LotteryCampaignCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryCampaignUpsertBulk) UpdateNewValues() *LotteryCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotterycampaign.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryCampaignUpsertBulk) Ignore() *LotteryCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryCampaignUpsertBulk) DoNothing() *LotteryCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryCampaignCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryCampaignUpsertBulk) Update(set func(*LotteryCampaignUpsert)) *LotteryCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryCampaignUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *LotteryCampaignUpsertBulk) SetName(v string) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateName() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *LotteryCampaignUpsertBulk) SetDescription(v string) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateDescription() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateDescription()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryCampaignUpsertBulk) SetStatus(v string) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateStatus() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateStatus()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *LotteryCampaignUpsertBulk) SetStartsAt(v time.Time) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateStartsAt() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *LotteryCampaignUpsertBulk) SetEndsAt(v time.Time) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateEndsAt() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *LotteryCampaignUpsertBulk) ClearEndsAt() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.ClearEndsAt()
	})
}

// SetChanceExpiresInDays sets the "chance_expires_in_days" field.
func (u *LotteryCampaignUpsertBulk) SetChanceExpiresInDays(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetChanceExpiresInDays(v)
	})
}

// AddChanceExpiresInDays adds v to the "chance_expires_in_days" field.
func (u *LotteryCampaignUpsertBulk) AddChanceExpiresInDays(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddChanceExpiresInDays(v)
	})
}

// UpdateChanceExpiresInDays sets the "chance_expires_in_days" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateChanceExpiresInDays() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateChanceExpiresInDays()
	})
}

// SetMetadata sets the "metadata" field.
func (u *LotteryCampaignUpsertBulk) SetMetadata(v map[string]interface{}) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateMetadata() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LotteryCampaignUpsertBulk) ClearMetadata() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.ClearMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryCampaignUpsertBulk) SetUpdatedAt(v time.Time) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateUpdatedAt() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryCampaignUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryCampaignCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryCampaignCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryCampaignUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
