// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycampaign"
	"github.com/Wei-Shaw/sub2api/ent/lotterychance"
	"github.com/Wei-Shaw/sub2api/ent/lotterydraw"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardaward"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardcampaign"
)

// LotteryCampaignQuery is the builder for querying LotteryCampaign entities.
type LotteryCampaignQuery struct {
	config
	ctx                        *QueryContext
	order                      []lotterycampaign.OrderOption
	inters                     []Interceptor
	predicates                 []predicate.LotteryCampaign
	withPrizes                 *LotteryPrizeQuery
	withChances                *LotteryChanceQuery
	withDraws                  *LotteryDrawQuery
	withRankingRewardCampaigns *RankingRewardCampaignQuery
	withRankingRewardAwards    *RankingRewardAwardQuery
	modifiers                  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LotteryCampaignQuery builder.
func (_q *LotteryCampaignQuery) Where(ps ...predicate.LotteryCampaign) *LotteryCampaignQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LotteryCampaignQuery) Limit(limit int) *LotteryCampaignQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LotteryCampaignQuery) Offset(offset int) *LotteryCampaignQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LotteryCampaignQuery) Unique(unique bool) *LotteryCampaignQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LotteryCampaignQuery) Order(o ...lotterycampaign.OrderOption) *LotteryCampaignQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPrizes chains the current query on the "prizes" edge.
func (_q *LotteryCampaignQuery) QueryPrizes() *LotteryPrizeQuery {
	query := (&LotteryPrizeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lotterycampaign.Table, lotterycampaign.FieldID, selector),
			sqlgraph.To(lotteryprize.Table, lotteryprize.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lotterycampaign.PrizesTable, lotterycampaign.PrizesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChances chains the current query on the "chances" edge.
func (_q *LotteryCampaignQuery) QueryChances() *LotteryChanceQuery {
	query := (&LotteryChanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lotterycampaign.Table, lotterycampaign.FieldID, selector),
			sqlgraph.To(lotterychance.Table, lotterychance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lotterycampaign.ChancesTable, lotterycampaign.ChancesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDraws chains the current query on the "draws" edge.
func (_q *LotteryCampaignQuery) QueryDraws() *LotteryDrawQuery {
	query := (&LotteryDrawClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lotterycampaign.Table, lotterycampaign.FieldID, selector),
			sqlgraph.To(lotterydraw.Table, lotterydraw.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lotterycampaign.DrawsTable, lotterycampaign.DrawsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRankingRewardCampaigns chains the current query on the "ranking_reward_campaigns" edge.
func (_q *LotteryCampaignQuery) QueryRankingRewardCampaigns() *RankingRewardCampaignQuery {
	query := (&RankingRewardCampaignClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lotterycampaign.Table, lotterycampaign.FieldID, selector),
			sqlgraph.To(rankingrewardcampaign.Table, rankingrewardcampaign.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lotterycampaign.RankingRewardCampaignsTable, lotterycampaign.RankingRewardCampaignsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRankingRewardAwards chains the current query on the "ranking_reward_awards" edge.
func (_q *LotteryCampaignQuery) QueryRankingRewardAwards() *RankingRewardAwardQuery {
	query := (&RankingRewardAwardClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lotterycampaign.Table, lotterycampaign.FieldID, selector),
			sqlgraph.To(rankingrewardaward.Table, rankingrewardaward.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lotterycampaign.RankingRewardAwardsTable, lotterycampaign.RankingRewardAwardsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LotteryCampaign entity from the query.
// Returns a *NotFoundError when no LotteryCampaign was found.
func (_q *LotteryCampaignQuery) First(ctx context.Context) (*LotteryCampaign, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lotterycampaign.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LotteryCampaignQuery) FirstX(ctx context.Context) *LotteryCampaign {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LotteryCampaign ID from the query.
// Returns a *NotFoundError when no LotteryCampaign ID was found.
func (_q *LotteryCampaignQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lotterycampaign.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *LotteryCampaignQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LotteryCampaign entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LotteryCampaign entity is found.
// Returns a *NotFoundError when no LotteryCampaign entities are found.
func (_q *LotteryCampaignQuery) Only(ctx context.Context) (*LotteryCampaign, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lotterycampaign.Label}
	default:
		return nil, &NotSingularError{lotterycampaign.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LotteryCampaignQuery) OnlyX(ctx context.Context) *LotteryCampaign {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LotteryCampaign ID in the query.
// Returns a *NotSingularError when more than one LotteryCampaign ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LotteryCampaignQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lotterycampaign.Label}
	default:
		err = &NotSingularError{lotterycampaign.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *LotteryCampaignQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LotteryCampaigns.
func (_q *LotteryCampaignQuery) All(ctx context.Context) ([]*LotteryCampaign, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LotteryCampaign, *LotteryCampaignQuery]()
	return withInterceptors[[]*LotteryCampaign](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LotteryCampaignQuery) AllX(ctx context.Context) []*LotteryCampaign {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LotteryCampaign IDs.
func (_q *LotteryCampaignQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(lotterycampaign.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *LotteryCampaignQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LotteryCampaignQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LotteryCampaignQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LotteryCampaignQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LotteryCampaignQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LotteryCampaignQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LotteryCampaignQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LotteryCampaignQuery) Clone() *LotteryCampaignQuery {
	if _q == nil {
		return nil
	}
	return &LotteryCampaignQuery{
		config:                     _q.config,
		ctx:                        _q.ctx.Clone(),
		order:                      append([]lotterycampaign.OrderOption{}, _q.order...),
		inters:                     append([]Interceptor{}, _q.inters...),
		predicates:                 append([]predicate.LotteryCampaign{}, _q.predicates...),
		withPrizes:                 _q.withPrizes.Clone(),
		withChances:                _q.withChances.Clone(),
		withDraws:                  _q.withDraws.Clone(),
		withRankingRewardCampaigns: _q.withRankingRewardCampaigns.Clone(),
		withRankingRewardAwards:    _q.withRankingRewardAwards.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPrizes tells the query-builder to eager-load the nodes that are connected to
// the "prizes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LotteryCampaignQuery) WithPrizes(opts ...func(*LotteryPrizeQuery)) *LotteryCampaignQuery {
	query := (&LotteryPrizeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPrizes = query
	return _q
}

// WithChances tells the query-builder to eager-load the nodes that are connected to
// the "chances" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LotteryCampaignQuery) WithChances(opts ...func(*LotteryChanceQuery)) *LotteryCampaignQuery {
	query := (&LotteryChanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChances = query
	return _q
}

// WithDraws tells the query-builder to eager-load the nodes that are connected to
// the "draws" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LotteryCampaignQuery) WithDraws(opts ...func(*LotteryDrawQuery)) *LotteryCampaignQuery {
	query := (&LotteryDrawClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDraws = query
	return _q
}

// WithRankingRewardCampaigns tells the query-builder to eager-load the nodes that are connected to
// the "ranking_reward_campaigns" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LotteryCampaignQuery) WithRankingRewardCampaigns(opts ...func(*RankingRewardCampaignQuery)) *LotteryCampaignQuery {
	query := (&RankingRewardCampaignClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRankingRewardCampaigns = query
	return _q
}

// WithRankingRewardAwards tells the query-builder to eager-load the nodes that are connected to
// the "ranking_reward_awards" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LotteryCampaignQuery) WithRankingRewardAwards(opts ...func(*RankingRewardAwardQuery)) *LotteryCampaignQuery {
	query := (&RankingRewardAwardClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRankingRewardAwards = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LotteryCampaign.Query().
//		GroupBy(lotterycampaign.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LotteryCampaignQuery) GroupBy(field string, fields ...string) *LotteryCampaignGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LotteryCampaignGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = lotterycampaign.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.LotteryCampaign.Query().
//		Select(lotterycampaign.FieldName).
//		Scan(ctx, &v)
func (_q *LotteryCampaignQuery) Select(fields ...string) *LotteryCampaignSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LotteryCampaignSelect{LotteryCampaignQuery: _q}
	sbuild.label = lotterycampaign.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LotteryCampaignSelect configured with the given aggregations.
func (_q *LotteryCampaignQuery) Aggregate(fns ...AggregateFunc) *LotteryCampaignSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LotteryCampaignQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !lotterycampaign.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LotteryCampaignQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LotteryCampaign, error) {
	var (
		nodes       = []*LotteryCampaign{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withPrizes != nil,
			_q.withChances != nil,
			_q.withDraws != nil,
			_q.withRankingRewardCampaigns != nil,
			_q.withRankingRewardAwards != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LotteryCampaign).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LotteryCampaign{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPrizes; query != nil {
		if err := _q.loadPrizes(ctx, query, nodes,
			func(n *LotteryCampaign) { n.Edges.Prizes = []*LotteryPrize{} },
			func(n *LotteryCampaign, e *LotteryPrize) { n.Edges.Prizes = append(n.Edges.Prizes, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChances; query != nil {
		if err := _q.loadChances(ctx, query, nodes,
			func(n *LotteryCampaign) { n.Edges.Chances = []*LotteryChance{} },
			func(n *LotteryCampaign, e *LotteryChance) { n.Edges.Chances = append(n.Edges.Chances, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDraws; query != nil {
		if err := _q.loadDraws(ctx, query, nodes,
			func(n *LotteryCampaign) { n.Edges.Draws = []*LotteryDraw{} },
			func(n *LotteryCampaign, e *LotteryDraw) { n.Edges.Draws = append(n.Edges.Draws, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRankingRewardCampaigns; query != nil {
		if err := _q.loadRankingRewardCampaigns(ctx, query, nodes,
			func(n *LotteryCampaign) { n.Edges.RankingRewardCampaigns = []*RankingRewardCampaign{} },
			func(n *LotteryCampaign, e *RankingRewardCampaign) {
				n.Edges.RankingRewardCampaigns = append(n.Edges.RankingRewardCampaigns, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withRankingRewardAwards; query != nil {
		if err := _q.loadRankingRewardAwards(ctx, query, nodes,
			func(n *LotteryCampaign) { n.Edges.RankingRewardAwards = []*RankingRewardAward{} },
			func(n *LotteryCampaign, e *RankingRewardAward) {
				n.Edges.RankingRewardAwards = append(n.Edges.RankingRewardAwards, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LotteryCampaignQuery) loadPrizes(ctx context.Context, query *LotteryPrizeQuery, nodes []*LotteryCampaign, init func(*LotteryCampaign), assign func(*LotteryCampaign, *LotteryPrize)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*LotteryCampaign)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(lotteryprize.FieldCampaignID)
	}
	query.Where(predicate.LotteryPrize(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(lotterycampaign.PrizesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CampaignID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "campaign_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *LotteryCampaignQuery) loadChances(ctx context.Context, query *LotteryChanceQuery, nodes []*LotteryCampaign, init func(*LotteryCampaign), assign func(*LotteryCampaign, *LotteryChance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*LotteryCampaign)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(lotterychance.FieldCampaignID)
	}
	query.Where(predicate.LotteryChance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(lotterycampaign.ChancesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CampaignID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "campaign_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *LotteryCampaignQuery) loadDraws(ctx context.Context, query *LotteryDrawQuery, nodes []*LotteryCampaign, init func(*LotteryCampaign), assign func(*LotteryCampaign, *LotteryDraw)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*LotteryCampaign)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(lotterydraw.FieldCampaignID)
	}
	query.Where(predicate.LotteryDraw(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(lotterycampaign.DrawsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CampaignID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "campaign_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *LotteryCampaignQuery) loadRankingRewardCampaigns(ctx context.Context, query *RankingRewardCampaignQuery, nodes []*LotteryCampaign, init func(*LotteryCampaign), assign func(*LotteryCampaign, *RankingRewardCampaign)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*LotteryCampaign)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rankingrewardcampaign.FieldLotteryCampaignID)
	}
	query.Where(predicate.RankingRewardCampaign(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(lotterycampaign.RankingRewardCampaignsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LotteryCampaignID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "lottery_campaign_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *LotteryCampaignQuery) loadRankingRewardAwards(ctx context.Context, query *RankingRewardAwardQuery, nodes []*LotteryCampaign, init func(*LotteryCampaign), assign func(*LotteryCampaign, *RankingRewardAward)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*LotteryCampaign)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rankingrewardaward.FieldLotteryCampaignID)
	}
	query.Where(predicate.RankingRewardAward(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(lotterycampaign.RankingRewardAwardsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LotteryCampaignID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "lottery_campaign_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *LotteryCampaignQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LotteryCampaignQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(lotterycampaign.Table, lotterycampaign.Columns, sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterycampaign.FieldID)
		for i := range fields {
			if fields[i] != lotterycampaign.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LotteryCampaignQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(lotterycampaign.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = lotterycampaign.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *LotteryCampaignQuery) ForUpdate(opts ...sql.LockOption) *LotteryCampaignQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *LotteryCampaignQuery) ForShare(opts ...sql.LockOption) *LotteryCampaignQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// LotteryCampaignGroupBy is the group-by builder for LotteryCampaign entities.
type LotteryCampaignGroupBy struct {
	selector
	build *LotteryCampaignQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LotteryCampaignGroupBy) Aggregate(fns ...AggregateFunc) *LotteryCampaignGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LotteryCampaignGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LotteryCampaignQuery, *LotteryCampaignGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LotteryCampaignGroupBy) sqlScan(ctx context.Context, root *LotteryCampaignQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LotteryCampaignSelect is the builder for selecting fields of LotteryCampaign entities.
type LotteryCampaignSelect struct {
	*LotteryCampaignQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LotteryCampaignSelect) Aggregate(fns ...AggregateFunc) *LotteryCampaignSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LotteryCampaignSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LotteryCampaignQuery, *LotteryCampaignSelect](ctx, _s.LotteryCampaignQuery, _s, _s.inters, v)
}

func (_s *LotteryCampaignSelect) sqlScan(ctx context.Context, root *LotteryCampaignQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
