// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycampaign"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardaward"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardcampaign"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardexcludeduser"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardrun"
)

// RankingRewardCampaignQuery is the builder for querying RankingRewardCampaign entities.
type RankingRewardCampaignQuery struct {
	config
	ctx                 *QueryContext
	order               []rankingrewardcampaign.OrderOption
	inters              []Interceptor
	predicates          []predicate.RankingRewardCampaign
	withLotteryCampaign *LotteryCampaignQuery
	withExcludedUsers   *RankingRewardExcludedUserQuery
	withRuns            *RankingRewardRunQuery
	withAwards          *RankingRewardAwardQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RankingRewardCampaignQuery builder.
func (_q *RankingRewardCampaignQuery) Where(ps ...predicate.RankingRewardCampaign) *RankingRewardCampaignQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RankingRewardCampaignQuery) Limit(limit int) *RankingRewardCampaignQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RankingRewardCampaignQuery) Offset(offset int) *RankingRewardCampaignQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RankingRewardCampaignQuery) Unique(unique bool) *RankingRewardCampaignQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RankingRewardCampaignQuery) Order(o ...rankingrewardcampaign.OrderOption) *RankingRewardCampaignQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLotteryCampaign chains the current query on the "lottery_campaign" edge.
func (_q *RankingRewardCampaignQuery) QueryLotteryCampaign() *LotteryCampaignQuery {
	query := (&LotteryCampaignClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rankingrewardcampaign.Table, rankingrewardcampaign.FieldID, selector),
			sqlgraph.To(lotterycampaign.Table, lotterycampaign.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rankingrewardcampaign.LotteryCampaignTable, rankingrewardcampaign.LotteryCampaignColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExcludedUsers chains the current query on the "excluded_users" edge.
func (_q *RankingRewardCampaignQuery) QueryExcludedUsers() *RankingRewardExcludedUserQuery {
	query := (&RankingRewardExcludedUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rankingrewardcampaign.Table, rankingrewardcampaign.FieldID, selector),
			sqlgraph.To(rankingrewardexcludeduser.Table, rankingrewardexcludeduser.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rankingrewardcampaign.ExcludedUsersTable, rankingrewardcampaign.ExcludedUsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRuns chains the current query on the "runs" edge.
func (_q *RankingRewardCampaignQuery) QueryRuns() *RankingRewardRunQuery {
	query := (&RankingRewardRunClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rankingrewardcampaign.Table, rankingrewardcampaign.FieldID, selector),
			sqlgraph.To(rankingrewardrun.Table, rankingrewardrun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rankingrewardcampaign.RunsTable, rankingrewardcampaign.RunsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAwards chains the current query on the "awards" edge.
func (_q *RankingRewardCampaignQuery) QueryAwards() *RankingRewardAwardQuery {
	query := (&RankingRewardAwardClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rankingrewardcampaign.Table, rankingrewardcampaign.FieldID, selector),
			sqlgraph.To(rankingrewardaward.Table, rankingrewardaward.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rankingrewardcampaign.AwardsTable, rankingrewardcampaign.AwardsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RankingRewardCampaign entity from the query.
// Returns a *NotFoundError when no RankingRewardCampaign was found.
func (_q *RankingRewardCampaignQuery) First(ctx context.Context) (*RankingRewardCampaign, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rankingrewardcampaign.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RankingRewardCampaignQuery) FirstX(ctx context.Context) *RankingRewardCampaign {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RankingRewardCampaign ID from the query.
// Returns a *NotFoundError when no RankingRewardCampaign ID was found.
func (_q *RankingRewardCampaignQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rankingrewardcampaign.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RankingRewardCampaignQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RankingRewardCampaign entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RankingRewardCampaign entity is found.
// Returns a *NotFoundError when no RankingRewardCampaign entities are found.
func (_q *RankingRewardCampaignQuery) Only(ctx context.Context) (*RankingRewardCampaign, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rankingrewardcampaign.Label}
	default:
		return nil, &NotSingularError{rankingrewardcampaign.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RankingRewardCampaignQuery) OnlyX(ctx context.Context) *RankingRewardCampaign {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RankingRewardCampaign ID in the query.
// Returns a *NotSingularError when more than one RankingRewardCampaign ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RankingRewardCampaignQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rankingrewardcampaign.Label}
	default:
		err = &NotSingularError{rankingrewardcampaign.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RankingRewardCampaignQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RankingRewardCampaigns.
func (_q *RankingRewardCampaignQuery) All(ctx context.Context) ([]*RankingRewardCampaign, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RankingRewardCampaign, *RankingRewardCampaignQuery]()
	return withInterceptors[[]*RankingRewardCampaign](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RankingRewardCampaignQuery) AllX(ctx context.Context) []*RankingRewardCampaign {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RankingRewardCampaign IDs.
func (_q *RankingRewardCampaignQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(rankingrewardcampaign.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RankingRewardCampaignQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RankingRewardCampaignQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RankingRewardCampaignQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RankingRewardCampaignQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RankingRewardCampaignQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RankingRewardCampaignQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RankingRewardCampaignQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RankingRewardCampaignQuery) Clone() *RankingRewardCampaignQuery {
	if _q == nil {
		return nil
	}
	return &RankingRewardCampaignQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]rankingrewardcampaign.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.RankingRewardCampaign{}, _q.predicates...),
		withLotteryCampaign: _q.withLotteryCampaign.Clone(),
		withExcludedUsers:   _q.withExcludedUsers.Clone(),
		withRuns:            _q.withRuns.Clone(),
		withAwards:          _q.withAwards.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithLotteryCampaign tells the query-builder to eager-load the nodes that are connected to
// the "lottery_campaign" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RankingRewardCampaignQuery) WithLotteryCampaign(opts ...func(*LotteryCampaignQuery)) *RankingRewardCampaignQuery {
	query := (&LotteryCampaignClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLotteryCampaign = query
	return _q
}

// WithExcludedUsers tells the query-builder to eager-load the nodes that are connected to
// the "excluded_users" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RankingRewardCampaignQuery) WithExcludedUsers(opts ...func(*RankingRewardExcludedUserQuery)) *RankingRewardCampaignQuery {
	query := (&RankingRewardExcludedUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withExcludedUsers = query
	return _q
}

// WithRuns tells the query-builder to eager-load the nodes that are connected to
// the "runs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RankingRewardCampaignQuery) WithRuns(opts ...func(*RankingRewardRunQuery)) *RankingRewardCampaignQuery {
	query := (&RankingRewardRunClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRuns = query
	return _q
}

// WithAwards tells the query-builder to eager-load the nodes that are connected to
// the "awards" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RankingRewardCampaignQuery) WithAwards(opts ...func(*RankingRewardAwardQuery)) *RankingRewardCampaignQuery {
	query := (&RankingRewardAwardClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAwards = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RankingRewardCampaign.Query().
//		GroupBy(rankingrewardcampaign.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RankingRewardCampaignQuery) GroupBy(field string, fields ...string) *RankingRewardCampaignGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RankingRewardCampaignGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = rankingrewardcampaign.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.RankingRewardCampaign.Query().
//		Select(rankingrewardcampaign.FieldName).
//		Scan(ctx, &v)
func (_q *RankingRewardCampaignQuery) Select(fields ...string) *RankingRewardCampaignSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RankingRewardCampaignSelect{RankingRewardCampaignQuery: _q}
	sbuild.label = rankingrewardcampaign.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RankingRewardCampaignSelect configured with the given aggregations.
func (_q *RankingRewardCampaignQuery) Aggregate(fns ...AggregateFunc) *RankingRewardCampaignSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RankingRewardCampaignQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !rankingrewardcampaign.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RankingRewardCampaignQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RankingRewardCampaign, error) {
	var (
		nodes       = []*RankingRewardCampaign{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withLotteryCampaign != nil,
			_q.withExcludedUsers != nil,
			_q.withRuns != nil,
			_q.withAwards != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RankingRewardCampaign).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RankingRewardCampaign{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLotteryCampaign; query != nil {
		if err := _q.loadLotteryCampaign(ctx, query, nodes, nil,
			func(n *RankingRewardCampaign, e *LotteryCampaign) { n.Edges.LotteryCampaign = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withExcludedUsers; query != nil {
		if err := _q.loadExcludedUsers(ctx, query, nodes,
			func(n *RankingRewardCampaign) { n.Edges.ExcludedUsers = []*RankingRewardExcludedUser{} },
			func(n *RankingRewardCampaign, e *RankingRewardExcludedUser) {
				n.Edges.ExcludedUsers = append(n.Edges.ExcludedUsers, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withRuns; query != nil {
		if err := _q.loadRuns(ctx, query, nodes,
			func(n *RankingRewardCampaign) { n.Edges.Runs = []*RankingRewardRun{} },
			func(n *RankingRewardCampaign, e *RankingRewardRun) { n.Edges.Runs = append(n.Edges.Runs, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAwards; query != nil {
		if err := _q.loadAwards(ctx, query, nodes,
			func(n *RankingRewardCampaign) { n.Edges.Awards = []*RankingRewardAward{} },
			func(n *RankingRewardCampaign, e *RankingRewardAward) { n.Edges.Awards = append(n.Edges.Awards, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RankingRewardCampaignQuery) loadLotteryCampaign(ctx context.Context, query *LotteryCampaignQuery, nodes []*RankingRewardCampaign, init func(*RankingRewardCampaign), assign func(*RankingRewardCampaign, *LotteryCampaign)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RankingRewardCampaign)
	for i := range nodes {
		fk := nodes[i].LotteryCampaignID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(lotterycampaign.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "lottery_campaign_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RankingRewardCampaignQuery) loadExcludedUsers(ctx context.Context, query *RankingRewardExcludedUserQuery, nodes []*RankingRewardCampaign, init func(*RankingRewardCampaign), assign func(*RankingRewardCampaign, *RankingRewardExcludedUser)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RankingRewardCampaign)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rankingrewardexcludeduser.FieldCampaignID)
	}
	query.Where(predicate.RankingRewardExcludedUser(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rankingrewardcampaign.ExcludedUsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CampaignID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "campaign_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RankingRewardCampaignQuery) loadRuns(ctx context.Context, query *RankingRewardRunQuery, nodes []*RankingRewardCampaign, init func(*RankingRewardCampaign), assign func(*RankingRewardCampaign, *RankingRewardRun)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RankingRewardCampaign)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rankingrewardrun.FieldCampaignID)
	}
	query.Where(predicate.RankingRewardRun(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rankingrewardcampaign.RunsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CampaignID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "campaign_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RankingRewardCampaignQuery) loadAwards(ctx context.Context, query *RankingRewardAwardQuery, nodes []*RankingRewardCampaign, init func(*RankingRewardCampaign), assign func(*RankingRewardCampaign, *RankingRewardAward)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RankingRewardCampaign)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rankingrewardaward.FieldCampaignID)
	}
	query.Where(predicate.RankingRewardAward(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rankingrewardcampaign.AwardsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CampaignID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "campaign_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RankingRewardCampaignQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RankingRewardCampaignQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rankingrewardcampaign.Table, rankingrewardcampaign.Columns, sqlgraph.NewFieldSpec(rankingrewardcampaign.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rankingrewardcampaign.FieldID)
		for i := range fields {
			if fields[i] != rankingrewardcampaign.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withLotteryCampaign != nil {
			_spec.Node.AddColumnOnce(rankingrewardcampaign.FieldLotteryCampaignID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RankingRewardCampaignQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(rankingrewardcampaign.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = rankingrewardcampaign.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RankingRewardCampaignQuery) ForUpdate(opts ...sql.LockOption) *RankingRewardCampaignQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RankingRewardCampaignQuery) ForShare(opts ...sql.LockOption) *RankingRewardCampaignQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// RankingRewardCampaignGroupBy is the group-by builder for RankingRewardCampaign entities.
type RankingRewardCampaignGroupBy struct {
	selector
	build *RankingRewardCampaignQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RankingRewardCampaignGroupBy) Aggregate(fns ...AggregateFunc) *RankingRewardCampaignGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RankingRewardCampaignGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RankingRewardCampaignQuery, *RankingRewardCampaignGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RankingRewardCampaignGroupBy) sqlScan(ctx context.Context, root *RankingRewardCampaignQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RankingRewardCampaignSelect is the builder for selecting fields of RankingRewardCampaign entities.
type RankingRewardCampaignSelect struct {
	*RankingRewardCampaignQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RankingRewardCampaignSelect) Aggregate(fns ...AggregateFunc) *RankingRewardCampaignSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RankingRewardCampaignSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RankingRewardCampaignQuery, *RankingRewardCampaignSelect](ctx, _s.RankingRewardCampaignQuery, _s, _s.inters, v)
}

func (_s *RankingRewardCampaignSelect) sqlScan(ctx context.Context, root *RankingRewardCampaignQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
