// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardaward"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardcampaign"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardrun"
)

// RankingRewardRunUpdate is the builder for updating RankingRewardRun entities.
type RankingRewardRunUpdate struct {
	config
	hooks    []Hook
	mutation *RankingRewardRunMutation
}

// Where appends a list predicates to the RankingRewardRunUpdate builder.
func (_u *RankingRewardRunUpdate) Where(ps ...predicate.RankingRewardRun) *RankingRewardRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *RankingRewardRunUpdate) SetCampaignID(v int64) *RankingRewardRunUpdate {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *RankingRewardRunUpdate) SetNillableCampaignID(v *int64) *RankingRewardRunUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetRewardDate sets the "reward_date" field.
func (_u *RankingRewardRunUpdate) SetRewardDate(v time.Time) *RankingRewardRunUpdate {
	_u.mutation.SetRewardDate(v)
	return _u
}

// SetNillableRewardDate sets the "reward_date" field if the given value is not nil.
func (_u *RankingRewardRunUpdate) SetNillableRewardDate(v *time.Time) *RankingRewardRunUpdate {
	if v != nil {
		_u.SetRewardDate(*v)
	}
	return _u
}

// SetWindowStart sets the "window_start" field.
func (_u *RankingRewardRunUpdate) SetWindowStart(v time.Time) *RankingRewardRunUpdate {
	_u.mutation.SetWindowStart(v)
	return _u
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_u *RankingRewardRunUpdate) SetNillableWindowStart(v *time.Time) *RankingRewardRunUpdate {
	if v != nil {
		_u.SetWindowStart(*v)
	}
	return _u
}

// SetWindowEnd sets the "window_end" field.
func (_u *RankingRewardRunUpdate) SetWindowEnd(v time.Time) *RankingRewardRunUpdate {
	_u.mutation.SetWindowEnd(v)
	return _u
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_u *RankingRewardRunUpdate) SetNillableWindowEnd(v *time.Time) *RankingRewardRunUpdate {
	if v != nil {
		_u.SetWindowEnd(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RankingRewardRunUpdate) SetStatus(v string) *RankingRewardRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RankingRewardRunUpdate) SetNillableStatus(v *string) *RankingRewardRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAwardedCount sets the "awarded_count" field.
func (_u *RankingRewardRunUpdate) SetAwardedCount(v int) *RankingRewardRunUpdate {
	_u.mutation.ResetAwardedCount()
	_u.mutation.SetAwardedCount(v)
	return _u
}

// SetNillableAwardedCount sets the "awarded_count" field if the given value is not nil.
func (_u *RankingRewardRunUpdate) SetNillableAwardedCount(v *int) *RankingRewardRunUpdate {
	if v != nil {
		_u.SetAwardedCount(*v)
	}
	return _u
}

// AddAwardedCount adds value to the "awarded_count" field.
func (_u *RankingRewardRunUpdate) AddAwardedCount(v int) *RankingRewardRunUpdate {
	_u.mutation.AddAwardedCount(v)
	return _u
}

// SetTotalActualCost sets the "total_actual_cost" field.
func (_u *RankingRewardRunUpdate) SetTotalActualCost(v float64) *RankingRewardRunUpdate {
	_u.mutation.ResetTotalActualCost()
	_u.mutation.SetTotalActualCost(v)
	return _u
}

// SetNillableTotalActualCost sets the "total_actual_cost" field if the given value is not nil.
func (_u *RankingRewardRunUpdate) SetNillableTotalActualCost(v *float64) *RankingRewardRunUpdate {
	if v != nil {
		_u.SetTotalActualCost(*v)
	}
	return _u
}

// AddTotalActualCost adds value to the "total_actual_cost" field.
func (_u *RankingRewardRunUpdate) AddTotalActualCost(v float64) *RankingRewardRunUpdate {
	_u.mutation.AddTotalActualCost(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RankingRewardRunUpdate) SetErrorMessage(v string) *RankingRewardRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RankingRewardRunUpdate) SetNillableErrorMessage(v *string) *RankingRewardRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RankingRewardRunUpdate) SetMetadata(v map[string]interface{}) *RankingRewardRunUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RankingRewardRunUpdate) ClearMetadata() *RankingRewardRunUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *RankingRewardRunUpdate) SetStartedAt(v time.Time) *RankingRewardRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *RankingRewardRunUpdate) SetNillableStartedAt(v *time.Time) *RankingRewardRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *RankingRewardRunUpdate) SetFinishedAt(v time.Time) *RankingRewardRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *RankingRewardRunUpdate) SetNillableFinishedAt(v *time.Time) *RankingRewardRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *RankingRewardRunUpdate) ClearFinishedAt() *RankingRewardRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RankingRewardRunUpdate) SetUpdatedAt(v time.Time) *RankingRewardRunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCampaign sets the "campaign" edge to the RankingRewardCampaign entity.
func (_u *RankingRewardRunUpdate) SetCampaign(v *RankingRewardCampaign) *RankingRewardRunUpdate {
	return _u.SetCampaignID(v.ID)
}

// AddAwardIDs adds the "awards" edge to the RankingRewardAward entity by IDs.
func (_u *RankingRewardRunUpdate) AddAwardIDs(ids ...int64) *RankingRewardRunUpdate {
	_u.mutation.AddAwardIDs(ids...)
	return _u
}

// AddAwards adds the "awards" edges to the RankingRewardAward entity.
func (_u *RankingRewardRunUpdate) AddAwards(v ...*RankingRewardAward) *RankingRewardRunUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAwardIDs(ids...)
}

// Mutation returns the RankingRewardRunMutation object of the builder.
func (_u *RankingRewardRunUpdate) Mutation() *RankingRewardRunMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the RankingRewardCampaign entity.
func (_u *RankingRewardRunUpdate) ClearCampaign() *RankingRewardRunUpdate {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearAwards clears all "awards" edges to the RankingRewardAward entity.
func (_u *RankingRewardRunUpdate) ClearAwards() *RankingRewardRunUpdate {
	_u.mutation.ClearAwards()
	return _u
}

// RemoveAwardIDs removes the "awards" edge to RankingRewardAward entities by IDs.
func (_u *RankingRewardRunUpdate) RemoveAwardIDs(ids ...int64) *RankingRewardRunUpdate {
	_u.mutation.RemoveAwardIDs(ids...)
	return _u
}

// RemoveAwards removes "awards" edges to RankingRewardAward entities.
func (_u *RankingRewardRunUpdate) RemoveAwards(v ...*RankingRewardAward) *RankingRewardRunUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAwardIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RankingRewardRunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RankingRewardRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RankingRewardRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RankingRewardRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RankingRewardRunUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rankingrewardrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RankingRewardRunUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := rankingrewardrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RankingRewardRun.status": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RankingRewardRun.campaign"`)
	}
	return nil
}

func (_u *RankingRewardRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rankingrewardrun.Table, rankingrewardrun.Columns, sqlgraph.NewFieldSpec(rankingrewardrun.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RewardDate(); ok {
		_spec.SetField(rankingrewardrun.FieldRewardDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WindowStart(); ok {
		_spec.SetField(rankingrewardrun.FieldWindowStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WindowEnd(); ok {
		_spec.SetField(rankingrewardrun.FieldWindowEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rankingrewardrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AwardedCount(); ok {
		_spec.SetField(rankingrewardrun.FieldAwardedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAwardedCount(); ok {
		_spec.AddField(rankingrewardrun.FieldAwardedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalActualCost(); ok {
		_spec.SetField(rankingrewardrun.FieldTotalActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalActualCost(); ok {
		_spec.AddField(rankingrewardrun.FieldTotalActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(rankingrewardrun.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(rankingrewardrun.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(rankingrewardrun.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(rankingrewardrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(rankingrewardrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(rankingrewardrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rankingrewardrun.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rankingrewardrun.CampaignTable,
			Columns: []string{rankingrewardrun.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardcampaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rankingrewardrun.CampaignTable,
			Columns: []string{rankingrewardrun.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardcampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardrun.AwardsTable,
			Columns: []string{rankingrewardrun.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAwardsIDs(); len(nodes) > 0 && !_u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardrun.AwardsTable,
			Columns: []string{rankingrewardrun.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardrun.AwardsTable,
			Columns: []string{rankingrewardrun.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rankingrewardrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RankingRewardRunUpdateOne is the builder for updating a single RankingRewardRun entity.
type RankingRewardRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RankingRewardRunMutation
}

// SetCampaignID sets the "campaign_id" field.
func (_u *RankingRewardRunUpdateOne) SetCampaignID(v int64) *RankingRewardRunUpdateOne {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *RankingRewardRunUpdateOne) SetNillableCampaignID(v *int64) *RankingRewardRunUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetRewardDate sets the "reward_date" field.
func (_u *RankingRewardRunUpdateOne) SetRewardDate(v time.Time) *RankingRewardRunUpdateOne {
	_u.mutation.SetRewardDate(v)
	return _u
}

// SetNillableRewardDate sets the "reward_date" field if the given value is not nil.
func (_u *RankingRewardRunUpdateOne) SetNillableRewardDate(v *time.Time) *RankingRewardRunUpdateOne {
	if v != nil {
		_u.SetRewardDate(*v)
	}
	return _u
}

// SetWindowStart sets the "window_start" field.
func (_u *RankingRewardRunUpdateOne) SetWindowStart(v time.Time) *RankingRewardRunUpdateOne {
	_u.mutation.SetWindowStart(v)
	return _u
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_u *RankingRewardRunUpdateOne) SetNillableWindowStart(v *time.Time) *RankingRewardRunUpdateOne {
	if v != nil {
		_u.SetWindowStart(*v)
	}
	return _u
}

// SetWindowEnd sets the "window_end" field.
func (_u *RankingRewardRunUpdateOne) SetWindowEnd(v time.Time) *RankingRewardRunUpdateOne {
	_u.mutation.SetWindowEnd(v)
	return _u
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_u *RankingRewardRunUpdateOne) SetNillableWindowEnd(v *time.Time) *RankingRewardRunUpdateOne {
	if v != nil {
		_u.SetWindowEnd(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RankingRewardRunUpdateOne) SetStatus(v string) *RankingRewardRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RankingRewardRunUpdateOne) SetNillableStatus(v *string) *RankingRewardRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAwardedCount sets the "awarded_count" field.
func (_u *RankingRewardRunUpdateOne) SetAwardedCount(v int) *RankingRewardRunUpdateOne {
	_u.mutation.ResetAwardedCount()
	_u.mutation.SetAwardedCount(v)
	return _u
}

// SetNillableAwardedCount sets the "awarded_count" field if the given value is not nil.
func (_u *RankingRewardRunUpdateOne) SetNillableAwardedCount(v *int) *RankingRewardRunUpdateOne {
	if v != nil {
		_u.SetAwardedCount(*v)
	}
	return _u
}

// AddAwardedCount adds value to the "awarded_count" field.
func (_u *RankingRewardRunUpdateOne) AddAwardedCount(v int) *RankingRewardRunUpdateOne {
	_u.mutation.AddAwardedCount(v)
	return _u
}

// SetTotalActualCost sets the "total_actual_cost" field.
func (_u *RankingRewardRunUpdateOne) SetTotalActualCost(v float64) *RankingRewardRunUpdateOne {
	_u.mutation.ResetTotalActualCost()
	_u.mutation.SetTotalActualCost(v)
	return _u
}

// SetNillableTotalActualCost sets the "total_actual_cost" field if the given value is not nil.
func (_u *RankingRewardRunUpdateOne) SetNillableTotalActualCost(v *float64) *RankingRewardRunUpdateOne {
	if v != nil {
		_u.SetTotalActualCost(*v)
	}
	return _u
}

// AddTotalActualCost adds value to the "total_actual_cost" field.
func (_u *RankingRewardRunUpdateOne) AddTotalActualCost(v float64) *RankingRewardRunUpdateOne {
	_u.mutation.AddTotalActualCost(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RankingRewardRunUpdateOne) SetErrorMessage(v string) *RankingRewardRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RankingRewardRunUpdateOne) SetNillableErrorMessage(v *string) *RankingRewardRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RankingRewardRunUpdateOne) SetMetadata(v map[string]interface{}) *RankingRewardRunUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RankingRewardRunUpdateOne) ClearMetadata() *RankingRewardRunUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *RankingRewardRunUpdateOne) SetStartedAt(v time.Time) *RankingRewardRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *RankingRewardRunUpdateOne) SetNillableStartedAt(v *time.Time) *RankingRewardRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *RankingRewardRunUpdateOne) SetFinishedAt(v time.Time) *RankingRewardRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *RankingRewardRunUpdateOne) SetNillableFinishedAt(v *time.Time) *RankingRewardRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *RankingRewardRunUpdateOne) ClearFinishedAt() *RankingRewardRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RankingRewardRunUpdateOne) SetUpdatedAt(v time.Time) *RankingRewardRunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCampaign sets the "campaign" edge to the RankingRewardCampaign entity.
func (_u *RankingRewardRunUpdateOne) SetCampaign(v *RankingRewardCampaign) *RankingRewardRunUpdateOne {
	return _u.SetCampaignID(v.ID)
}

// AddAwardIDs adds the "awards" edge to the RankingRewardAward entity by IDs.
func (_u *RankingRewardRunUpdateOne) AddAwardIDs(ids ...int64) *RankingRewardRunUpdateOne {
	_u.mutation.AddAwardIDs(ids...)
	return _u
}

// AddAwards adds the "awards" edges to the RankingRewardAward entity.
func (_u *RankingRewardRunUpdateOne) AddAwards(v ...*RankingRewardAward) *RankingRewardRunUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAwardIDs(ids...)
}

// Mutation returns the RankingRewardRunMutation object of the builder.
func (_u *RankingRewardRunUpdateOne) Mutation() *RankingRewardRunMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the RankingRewardCampaign entity.
func (_u *RankingRewardRunUpdateOne) ClearCampaign() *RankingRewardRunUpdateOne {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearAwards clears all "awards" edges to the RankingRewardAward entity.
func (_u *RankingRewardRunUpdateOne) ClearAwards() *RankingRewardRunUpdateOne {
	_u.mutation.ClearAwards()
	return _u
}

// RemoveAwardIDs removes the "awards" edge to RankingRewardAward entities by IDs.
func (_u *RankingRewardRunUpdateOne) RemoveAwardIDs(ids ...int64) *RankingRewardRunUpdateOne {
	_u.mutation.RemoveAwardIDs(ids...)
	return _u
}

// RemoveAwards removes "awards" edges to RankingRewardAward entities.
func (_u *RankingRewardRunUpdateOne) RemoveAwards(v ...*RankingRewardAward) *RankingRewardRunUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAwardIDs(ids...)
}

// Where appends a list predicates to the RankingRewardRunUpdate builder.
func (_u *RankingRewardRunUpdateOne) Where(ps ...predicate.RankingRewardRun) *RankingRewardRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RankingRewardRunUpdateOne) Select(field string, fields ...string) *RankingRewardRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RankingRewardRun entity.
func (_u *RankingRewardRunUpdateOne) Save(ctx context.Context) (*RankingRewardRun, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RankingRewardRunUpdateOne) SaveX(ctx context.Context) *RankingRewardRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RankingRewardRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RankingRewardRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RankingRewardRunUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rankingrewardrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RankingRewardRunUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := rankingrewardrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RankingRewardRun.status": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RankingRewardRun.campaign"`)
	}
	return nil
}

func (_u *RankingRewardRunUpdateOne) sqlSave(ctx context.Context) (_node *RankingRewardRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rankingrewardrun.Table, rankingrewardrun.Columns, sqlgraph.NewFieldSpec(rankingrewardrun.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RankingRewardRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rankingrewardrun.FieldID)
		for _, f := range fields {
			if !rankingrewardrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rankingrewardrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RewardDate(); ok {
		_spec.SetField(rankingrewardrun.FieldRewardDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WindowStart(); ok {
		_spec.SetField(rankingrewardrun.FieldWindowStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WindowEnd(); ok {
		_spec.SetField(rankingrewardrun.FieldWindowEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rankingrewardrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AwardedCount(); ok {
		_spec.SetField(rankingrewardrun.FieldAwardedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAwardedCount(); ok {
		_spec.AddField(rankingrewardrun.FieldAwardedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalActualCost(); ok {
		_spec.SetField(rankingrewardrun.FieldTotalActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalActualCost(); ok {
		_spec.AddField(rankingrewardrun.FieldTotalActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(rankingrewardrun.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(rankingrewardrun.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(rankingrewardrun.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(rankingrewardrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(rankingrewardrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(rankingrewardrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rankingrewardrun.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rankingrewardrun.CampaignTable,
			Columns: []string{rankingrewardrun.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardcampaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rankingrewardrun.CampaignTable,
			Columns: []string{rankingrewardrun.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardcampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardrun.AwardsTable,
			Columns: []string{rankingrewardrun.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAwardsIDs(); len(nodes) > 0 && !_u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardrun.AwardsTable,
			Columns: []string{rankingrewardrun.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardrun.AwardsTable,
			Columns: []string{rankingrewardrun.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RankingRewardRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rankingrewardrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
