// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycampaign"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardaward"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardcampaign"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardexcludeduser"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardrun"
)

// RankingRewardCampaignUpdate is the builder for updating RankingRewardCampaign entities.
type RankingRewardCampaignUpdate struct {
	config
	hooks    []Hook
	mutation *RankingRewardCampaignMutation
}

// Where appends a list predicates to the RankingRewardCampaignUpdate builder.
func (_u *RankingRewardCampaignUpdate) Where(ps ...predicate.RankingRewardCampaign) *RankingRewardCampaignUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RankingRewardCampaignUpdate) SetName(v string) *RankingRewardCampaignUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableName(v *string) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RankingRewardCampaignUpdate) SetDescription(v string) *RankingRewardCampaignUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableDescription(v *string) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RankingRewardCampaignUpdate) SetStatus(v string) *RankingRewardCampaignUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableStatus(v *string) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLotteryCampaignID sets the "lottery_campaign_id" field.
func (_u *RankingRewardCampaignUpdate) SetLotteryCampaignID(v int64) *RankingRewardCampaignUpdate {
	_u.mutation.SetLotteryCampaignID(v)
	return _u
}

// SetNillableLotteryCampaignID sets the "lottery_campaign_id" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableLotteryCampaignID(v *int64) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetLotteryCampaignID(*v)
	}
	return _u
}

// SetTopN sets the "top_n" field.
func (_u *RankingRewardCampaignUpdate) SetTopN(v int) *RankingRewardCampaignUpdate {
	_u.mutation.ResetTopN()
	_u.mutation.SetTopN(v)
	return _u
}

// SetNillableTopN sets the "top_n" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableTopN(v *int) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetTopN(*v)
	}
	return _u
}

// AddTopN adds value to the "top_n" field.
func (_u *RankingRewardCampaignUpdate) AddTopN(v int) *RankingRewardCampaignUpdate {
	_u.mutation.AddTopN(v)
	return _u
}

// SetChanceCount sets the "chance_count" field.
func (_u *RankingRewardCampaignUpdate) SetChanceCount(v int) *RankingRewardCampaignUpdate {
	_u.mutation.ResetChanceCount()
	_u.mutation.SetChanceCount(v)
	return _u
}

// SetNillableChanceCount sets the "chance_count" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableChanceCount(v *int) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetChanceCount(*v)
	}
	return _u
}

// AddChanceCount adds value to the "chance_count" field.
func (_u *RankingRewardCampaignUpdate) AddChanceCount(v int) *RankingRewardCampaignUpdate {
	_u.mutation.AddChanceCount(v)
	return _u
}

// SetPublicDisplayLimit sets the "public_display_limit" field.
func (_u *RankingRewardCampaignUpdate) SetPublicDisplayLimit(v int) *RankingRewardCampaignUpdate {
	_u.mutation.ResetPublicDisplayLimit()
	_u.mutation.SetPublicDisplayLimit(v)
	return _u
}

// SetNillablePublicDisplayLimit sets the "public_display_limit" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillablePublicDisplayLimit(v *int) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetPublicDisplayLimit(*v)
	}
	return _u
}

// AddPublicDisplayLimit adds value to the "public_display_limit" field.
func (_u *RankingRewardCampaignUpdate) AddPublicDisplayLimit(v int) *RankingRewardCampaignUpdate {
	_u.mutation.AddPublicDisplayLimit(v)
	return _u
}

// SetMinActualCost sets the "min_actual_cost" field.
func (_u *RankingRewardCampaignUpdate) SetMinActualCost(v float64) *RankingRewardCampaignUpdate {
	_u.mutation.ResetMinActualCost()
	_u.mutation.SetMinActualCost(v)
	return _u
}

// SetNillableMinActualCost sets the "min_actual_cost" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableMinActualCost(v *float64) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetMinActualCost(*v)
	}
	return _u
}

// AddMinActualCost adds value to the "min_actual_cost" field.
func (_u *RankingRewardCampaignUpdate) AddMinActualCost(v float64) *RankingRewardCampaignUpdate {
	_u.mutation.AddMinActualCost(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *RankingRewardCampaignUpdate) SetStartsAt(v time.Time) *RankingRewardCampaignUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableStartsAt(v *time.Time) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *RankingRewardCampaignUpdate) SetEndsAt(v time.Time) *RankingRewardCampaignUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableEndsAt(v *time.Time) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *RankingRewardCampaignUpdate) ClearEndsAt() *RankingRewardCampaignUpdate {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *RankingRewardCampaignUpdate) SetTimezone(v string) *RankingRewardCampaignUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableTimezone(v *string) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetLastRunDate sets the "last_run_date" field.
func (_u *RankingRewardCampaignUpdate) SetLastRunDate(v time.Time) *RankingRewardCampaignUpdate {
	_u.mutation.SetLastRunDate(v)
	return _u
}

// SetNillableLastRunDate sets the "last_run_date" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdate) SetNillableLastRunDate(v *time.Time) *RankingRewardCampaignUpdate {
	if v != nil {
		_u.SetLastRunDate(*v)
	}
	return _u
}

// ClearLastRunDate clears the value of the "last_run_date" field.
func (_u *RankingRewardCampaignUpdate) ClearLastRunDate() *RankingRewardCampaignUpdate {
	_u.mutation.ClearLastRunDate()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RankingRewardCampaignUpdate) SetMetadata(v map[string]interface{}) *RankingRewardCampaignUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RankingRewardCampaignUpdate) ClearMetadata() *RankingRewardCampaignUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RankingRewardCampaignUpdate) SetUpdatedAt(v time.Time) *RankingRewardCampaignUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLotteryCampaign sets the "lottery_campaign" edge to the LotteryCampaign entity.
func (_u *RankingRewardCampaignUpdate) SetLotteryCampaign(v *LotteryCampaign) *RankingRewardCampaignUpdate {
	return _u.SetLotteryCampaignID(v.ID)
}

// AddExcludedUserIDs adds the "excluded_users" edge to the RankingRewardExcludedUser entity by IDs.
func (_u *RankingRewardCampaignUpdate) AddExcludedUserIDs(ids ...int64) *RankingRewardCampaignUpdate {
	_u.mutation.AddExcludedUserIDs(ids...)
	return _u
}

// AddExcludedUsers adds the "excluded_users" edges to the RankingRewardExcludedUser entity.
func (_u *RankingRewardCampaignUpdate) AddExcludedUsers(v ...*RankingRewardExcludedUser) *RankingRewardCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExcludedUserIDs(ids...)
}

// AddRunIDs adds the "runs" edge to the RankingRewardRun entity by IDs.
func (_u *RankingRewardCampaignUpdate) AddRunIDs(ids ...int64) *RankingRewardCampaignUpdate {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the RankingRewardRun entity.
func (_u *RankingRewardCampaignUpdate) AddRuns(v ...*RankingRewardRun) *RankingRewardCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// AddAwardIDs adds the "awards" edge to the RankingRewardAward entity by IDs.
func (_u *RankingRewardCampaignUpdate) AddAwardIDs(ids ...int64) *RankingRewardCampaignUpdate {
	_u.mutation.AddAwardIDs(ids...)
	return _u
}

// AddAwards adds the "awards" edges to the RankingRewardAward entity.
func (_u *RankingRewardCampaignUpdate) AddAwards(v ...*RankingRewardAward) *RankingRewardCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAwardIDs(ids...)
}

// Mutation returns the RankingRewardCampaignMutation object of the builder.
func (_u *RankingRewardCampaignUpdate) Mutation() *RankingRewardCampaignMutation {
	return _u.mutation
}

// ClearLotteryCampaign clears the "lottery_campaign" edge to the LotteryCampaign entity.
func (_u *RankingRewardCampaignUpdate) ClearLotteryCampaign() *RankingRewardCampaignUpdate {
	_u.mutation.ClearLotteryCampaign()
	return _u
}

// ClearExcludedUsers clears all "excluded_users" edges to the RankingRewardExcludedUser entity.
func (_u *RankingRewardCampaignUpdate) ClearExcludedUsers() *RankingRewardCampaignUpdate {
	_u.mutation.ClearExcludedUsers()
	return _u
}

// RemoveExcludedUserIDs removes the "excluded_users" edge to RankingRewardExcludedUser entities by IDs.
func (_u *RankingRewardCampaignUpdate) RemoveExcludedUserIDs(ids ...int64) *RankingRewardCampaignUpdate {
	_u.mutation.RemoveExcludedUserIDs(ids...)
	return _u
}

// RemoveExcludedUsers removes "excluded_users" edges to RankingRewardExcludedUser entities.
func (_u *RankingRewardCampaignUpdate) RemoveExcludedUsers(v ...*RankingRewardExcludedUser) *RankingRewardCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExcludedUserIDs(ids...)
}

// ClearRuns clears all "runs" edges to the RankingRewardRun entity.
func (_u *RankingRewardCampaignUpdate) ClearRuns() *RankingRewardCampaignUpdate {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to RankingRewardRun entities by IDs.
func (_u *RankingRewardCampaignUpdate) RemoveRunIDs(ids ...int64) *RankingRewardCampaignUpdate {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to RankingRewardRun entities.
func (_u *RankingRewardCampaignUpdate) RemoveRuns(v ...*RankingRewardRun) *RankingRewardCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// ClearAwards clears all "awards" edges to the RankingRewardAward entity.
func (_u *RankingRewardCampaignUpdate) ClearAwards() *RankingRewardCampaignUpdate {
	_u.mutation.ClearAwards()
	return _u
}

// RemoveAwardIDs removes the "awards" edge to RankingRewardAward entities by IDs.
func (_u *RankingRewardCampaignUpdate) RemoveAwardIDs(ids ...int64) *RankingRewardCampaignUpdate {
	_u.mutation.RemoveAwardIDs(ids...)
	return _u
}

// RemoveAwards removes "awards" edges to RankingRewardAward entities.
func (_u *RankingRewardCampaignUpdate) RemoveAwards(v ...*RankingRewardAward) *RankingRewardCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAwardIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RankingRewardCampaignUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RankingRewardCampaignUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RankingRewardCampaignUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RankingRewardCampaignUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RankingRewardCampaignUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rankingrewardcampaign.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RankingRewardCampaignUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rankingrewardcampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rankingrewardcampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TopN(); ok {
		if err := rankingrewardcampaign.TopNValidator(v); err != nil {
			return &ValidationError{Name: "top_n", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.top_n": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChanceCount(); ok {
		if err := rankingrewardcampaign.ChanceCountValidator(v); err != nil {
			return &ValidationError{Name: "chance_count", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.chance_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicDisplayLimit(); ok {
		if err := rankingrewardcampaign.PublicDisplayLimitValidator(v); err != nil {
			return &ValidationError{Name: "public_display_limit", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.public_display_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := rankingrewardcampaign.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.timezone": %w`, err)}
		}
	}
	if _u.mutation.LotteryCampaignCleared() && len(_u.mutation.LotteryCampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RankingRewardCampaign.lottery_campaign"`)
	}
	return nil
}

func (_u *RankingRewardCampaignUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rankingrewardcampaign.Table, rankingrewardcampaign.Columns, sqlgraph.NewFieldSpec(rankingrewardcampaign.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rankingrewardcampaign.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rankingrewardcampaign.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rankingrewardcampaign.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TopN(); ok {
		_spec.SetField(rankingrewardcampaign.FieldTopN, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTopN(); ok {
		_spec.AddField(rankingrewardcampaign.FieldTopN, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChanceCount(); ok {
		_spec.SetField(rankingrewardcampaign.FieldChanceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChanceCount(); ok {
		_spec.AddField(rankingrewardcampaign.FieldChanceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PublicDisplayLimit(); ok {
		_spec.SetField(rankingrewardcampaign.FieldPublicDisplayLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPublicDisplayLimit(); ok {
		_spec.AddField(rankingrewardcampaign.FieldPublicDisplayLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinActualCost(); ok {
		_spec.SetField(rankingrewardcampaign.FieldMinActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinActualCost(); ok {
		_spec.AddField(rankingrewardcampaign.FieldMinActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(rankingrewardcampaign.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(rankingrewardcampaign.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(rankingrewardcampaign.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(rankingrewardcampaign.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastRunDate(); ok {
		_spec.SetField(rankingrewardcampaign.FieldLastRunDate, field.TypeTime, value)
	}
	if _u.mutation.LastRunDateCleared() {
		_spec.ClearField(rankingrewardcampaign.FieldLastRunDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(rankingrewardcampaign.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(rankingrewardcampaign.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rankingrewardcampaign.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LotteryCampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rankingrewardcampaign.LotteryCampaignTable,
			Columns: []string{rankingrewardcampaign.LotteryCampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LotteryCampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rankingrewardcampaign.LotteryCampaignTable,
			Columns: []string{rankingrewardcampaign.LotteryCampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExcludedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.ExcludedUsersTable,
			Columns: []string{rankingrewardcampaign.ExcludedUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardexcludeduser.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExcludedUsersIDs(); len(nodes) > 0 && !_u.mutation.ExcludedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.ExcludedUsersTable,
			Columns: []string{rankingrewardcampaign.ExcludedUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardexcludeduser.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExcludedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.ExcludedUsersTable,
			Columns: []string{rankingrewardcampaign.ExcludedUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardexcludeduser.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.RunsTable,
			Columns: []string{rankingrewardcampaign.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardrun.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.RunsTable,
			Columns: []string{rankingrewardcampaign.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.RunsTable,
			Columns: []string{rankingrewardcampaign.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.AwardsTable,
			Columns: []string{rankingrewardcampaign.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAwardsIDs(); len(nodes) > 0 && !_u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.AwardsTable,
			Columns: []string{rankingrewardcampaign.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.AwardsTable,
			Columns: []string{rankingrewardcampaign.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rankingrewardcampaign.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RankingRewardCampaignUpdateOne is the builder for updating a single RankingRewardCampaign entity.
type RankingRewardCampaignUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RankingRewardCampaignMutation
}

// SetName sets the "name" field.
func (_u *RankingRewardCampaignUpdateOne) SetName(v string) *RankingRewardCampaignUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableName(v *string) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RankingRewardCampaignUpdateOne) SetDescription(v string) *RankingRewardCampaignUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableDescription(v *string) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RankingRewardCampaignUpdateOne) SetStatus(v string) *RankingRewardCampaignUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableStatus(v *string) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLotteryCampaignID sets the "lottery_campaign_id" field.
func (_u *RankingRewardCampaignUpdateOne) SetLotteryCampaignID(v int64) *RankingRewardCampaignUpdateOne {
	_u.mutation.SetLotteryCampaignID(v)
	return _u
}

// SetNillableLotteryCampaignID sets the "lottery_campaign_id" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableLotteryCampaignID(v *int64) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetLotteryCampaignID(*v)
	}
	return _u
}

// SetTopN sets the "top_n" field.
func (_u *RankingRewardCampaignUpdateOne) SetTopN(v int) *RankingRewardCampaignUpdateOne {
	_u.mutation.ResetTopN()
	_u.mutation.SetTopN(v)
	return _u
}

// SetNillableTopN sets the "top_n" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableTopN(v *int) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetTopN(*v)
	}
	return _u
}

// AddTopN adds value to the "top_n" field.
func (_u *RankingRewardCampaignUpdateOne) AddTopN(v int) *RankingRewardCampaignUpdateOne {
	_u.mutation.AddTopN(v)
	return _u
}

// SetChanceCount sets the "chance_count" field.
func (_u *RankingRewardCampaignUpdateOne) SetChanceCount(v int) *RankingRewardCampaignUpdateOne {
	_u.mutation.ResetChanceCount()
	_u.mutation.SetChanceCount(v)
	return _u
}

// SetNillableChanceCount sets the "chance_count" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableChanceCount(v *int) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetChanceCount(*v)
	}
	return _u
}

// AddChanceCount adds value to the "chance_count" field.
func (_u *RankingRewardCampaignUpdateOne) AddChanceCount(v int) *RankingRewardCampaignUpdateOne {
	_u.mutation.AddChanceCount(v)
	return _u
}

// SetPublicDisplayLimit sets the "public_display_limit" field.
func (_u *RankingRewardCampaignUpdateOne) SetPublicDisplayLimit(v int) *RankingRewardCampaignUpdateOne {
	_u.mutation.ResetPublicDisplayLimit()
	_u.mutation.SetPublicDisplayLimit(v)
	return _u
}

// SetNillablePublicDisplayLimit sets the "public_display_limit" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillablePublicDisplayLimit(v *int) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetPublicDisplayLimit(*v)
	}
	return _u
}

// AddPublicDisplayLimit adds value to the "public_display_limit" field.
func (_u *RankingRewardCampaignUpdateOne) AddPublicDisplayLimit(v int) *RankingRewardCampaignUpdateOne {
	_u.mutation.AddPublicDisplayLimit(v)
	return _u
}

// SetMinActualCost sets the "min_actual_cost" field.
func (_u *RankingRewardCampaignUpdateOne) SetMinActualCost(v float64) *RankingRewardCampaignUpdateOne {
	_u.mutation.ResetMinActualCost()
	_u.mutation.SetMinActualCost(v)
	return _u
}

// SetNillableMinActualCost sets the "min_actual_cost" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableMinActualCost(v *float64) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetMinActualCost(*v)
	}
	return _u
}

// AddMinActualCost adds value to the "min_actual_cost" field.
func (_u *RankingRewardCampaignUpdateOne) AddMinActualCost(v float64) *RankingRewardCampaignUpdateOne {
	_u.mutation.AddMinActualCost(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *RankingRewardCampaignUpdateOne) SetStartsAt(v time.Time) *RankingRewardCampaignUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableStartsAt(v *time.Time) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *RankingRewardCampaignUpdateOne) SetEndsAt(v time.Time) *RankingRewardCampaignUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableEndsAt(v *time.Time) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *RankingRewardCampaignUpdateOne) ClearEndsAt() *RankingRewardCampaignUpdateOne {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *RankingRewardCampaignUpdateOne) SetTimezone(v string) *RankingRewardCampaignUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableTimezone(v *string) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetLastRunDate sets the "last_run_date" field.
func (_u *RankingRewardCampaignUpdateOne) SetLastRunDate(v time.Time) *RankingRewardCampaignUpdateOne {
	_u.mutation.SetLastRunDate(v)
	return _u
}

// SetNillableLastRunDate sets the "last_run_date" field if the given value is not nil.
func (_u *RankingRewardCampaignUpdateOne) SetNillableLastRunDate(v *time.Time) *RankingRewardCampaignUpdateOne {
	if v != nil {
		_u.SetLastRunDate(*v)
	}
	return _u
}

// ClearLastRunDate clears the value of the "last_run_date" field.
func (_u *RankingRewardCampaignUpdateOne) ClearLastRunDate() *RankingRewardCampaignUpdateOne {
	_u.mutation.ClearLastRunDate()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RankingRewardCampaignUpdateOne) SetMetadata(v map[string]interface{}) *RankingRewardCampaignUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RankingRewardCampaignUpdateOne) ClearMetadata() *RankingRewardCampaignUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RankingRewardCampaignUpdateOne) SetUpdatedAt(v time.Time) *RankingRewardCampaignUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLotteryCampaign sets the "lottery_campaign" edge to the LotteryCampaign entity.
func (_u *RankingRewardCampaignUpdateOne) SetLotteryCampaign(v *LotteryCampaign) *RankingRewardCampaignUpdateOne {
	return _u.SetLotteryCampaignID(v.ID)
}

// AddExcludedUserIDs adds the "excluded_users" edge to the RankingRewardExcludedUser entity by IDs.
func (_u *RankingRewardCampaignUpdateOne) AddExcludedUserIDs(ids ...int64) *RankingRewardCampaignUpdateOne {
	_u.mutation.AddExcludedUserIDs(ids...)
	return _u
}

// AddExcludedUsers adds the "excluded_users" edges to the RankingRewardExcludedUser entity.
func (_u *RankingRewardCampaignUpdateOne) AddExcludedUsers(v ...*RankingRewardExcludedUser) *RankingRewardCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExcludedUserIDs(ids...)
}

// AddRunIDs adds the "runs" edge to the RankingRewardRun entity by IDs.
func (_u *RankingRewardCampaignUpdateOne) AddRunIDs(ids ...int64) *RankingRewardCampaignUpdateOne {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the RankingRewardRun entity.
func (_u *RankingRewardCampaignUpdateOne) AddRuns(v ...*RankingRewardRun) *RankingRewardCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// AddAwardIDs adds the "awards" edge to the RankingRewardAward entity by IDs.
func (_u *RankingRewardCampaignUpdateOne) AddAwardIDs(ids ...int64) *RankingRewardCampaignUpdateOne {
	_u.mutation.AddAwardIDs(ids...)
	return _u
}

// AddAwards adds the "awards" edges to the RankingRewardAward entity.
func (_u *RankingRewardCampaignUpdateOne) AddAwards(v ...*RankingRewardAward) *RankingRewardCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAwardIDs(ids...)
}

// Mutation returns the RankingRewardCampaignMutation object of the builder.
func (_u *RankingRewardCampaignUpdateOne) Mutation() *RankingRewardCampaignMutation {
	return _u.mutation
}

// ClearLotteryCampaign clears the "lottery_campaign" edge to the LotteryCampaign entity.
func (_u *RankingRewardCampaignUpdateOne) ClearLotteryCampaign() *RankingRewardCampaignUpdateOne {
	_u.mutation.ClearLotteryCampaign()
	return _u
}

// ClearExcludedUsers clears all "excluded_users" edges to the RankingRewardExcludedUser entity.
func (_u *RankingRewardCampaignUpdateOne) ClearExcludedUsers() *RankingRewardCampaignUpdateOne {
	_u.mutation.ClearExcludedUsers()
	return _u
}

// RemoveExcludedUserIDs removes the "excluded_users" edge to RankingRewardExcludedUser entities by IDs.
func (_u *RankingRewardCampaignUpdateOne) RemoveExcludedUserIDs(ids ...int64) *RankingRewardCampaignUpdateOne {
	_u.mutation.RemoveExcludedUserIDs(ids...)
	return _u
}

// RemoveExcludedUsers removes "excluded_users" edges to RankingRewardExcludedUser entities.
func (_u *RankingRewardCampaignUpdateOne) RemoveExcludedUsers(v ...*RankingRewardExcludedUser) *RankingRewardCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExcludedUserIDs(ids...)
}

// ClearRuns clears all "runs" edges to the RankingRewardRun entity.
func (_u *RankingRewardCampaignUpdateOne) ClearRuns() *RankingRewardCampaignUpdateOne {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to RankingRewardRun entities by IDs.
func (_u *RankingRewardCampaignUpdateOne) RemoveRunIDs(ids ...int64) *RankingRewardCampaignUpdateOne {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to RankingRewardRun entities.
func (_u *RankingRewardCampaignUpdateOne) RemoveRuns(v ...*RankingRewardRun) *RankingRewardCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// ClearAwards clears all "awards" edges to the RankingRewardAward entity.
func (_u *RankingRewardCampaignUpdateOne) ClearAwards() *RankingRewardCampaignUpdateOne {
	_u.mutation.ClearAwards()
	return _u
}

// RemoveAwardIDs removes the "awards" edge to RankingRewardAward entities by IDs.
func (_u *RankingRewardCampaignUpdateOne) RemoveAwardIDs(ids ...int64) *RankingRewardCampaignUpdateOne {
	_u.mutation.RemoveAwardIDs(ids...)
	return _u
}

// RemoveAwards removes "awards" edges to RankingRewardAward entities.
func (_u *RankingRewardCampaignUpdateOne) RemoveAwards(v ...*RankingRewardAward) *RankingRewardCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAwardIDs(ids...)
}

// Where appends a list predicates to the RankingRewardCampaignUpdate builder.
func (_u *RankingRewardCampaignUpdateOne) Where(ps ...predicate.RankingRewardCampaign) *RankingRewardCampaignUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RankingRewardCampaignUpdateOne) Select(field string, fields ...string) *RankingRewardCampaignUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RankingRewardCampaign entity.
func (_u *RankingRewardCampaignUpdateOne) Save(ctx context.Context) (*RankingRewardCampaign, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RankingRewardCampaignUpdateOne) SaveX(ctx context.Context) *RankingRewardCampaign {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RankingRewardCampaignUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RankingRewardCampaignUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RankingRewardCampaignUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rankingrewardcampaign.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RankingRewardCampaignUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rankingrewardcampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rankingrewardcampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TopN(); ok {
		if err := rankingrewardcampaign.TopNValidator(v); err != nil {
			return &ValidationError{Name: "top_n", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.top_n": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChanceCount(); ok {
		if err := rankingrewardcampaign.ChanceCountValidator(v); err != nil {
			return &ValidationError{Name: "chance_count", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.chance_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicDisplayLimit(); ok {
		if err := rankingrewardcampaign.PublicDisplayLimitValidator(v); err != nil {
			return &ValidationError{Name: "public_display_limit", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.public_display_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := rankingrewardcampaign.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "RankingRewardCampaign.timezone": %w`, err)}
		}
	}
	if _u.mutation.LotteryCampaignCleared() && len(_u.mutation.LotteryCampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RankingRewardCampaign.lottery_campaign"`)
	}
	return nil
}

func (_u *RankingRewardCampaignUpdateOne) sqlSave(ctx context.Context) (_node *RankingRewardCampaign, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rankingrewardcampaign.Table, rankingrewardcampaign.Columns, sqlgraph.NewFieldSpec(rankingrewardcampaign.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RankingRewardCampaign.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rankingrewardcampaign.FieldID)
		for _, f := range fields {
			if !rankingrewardcampaign.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rankingrewardcampaign.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rankingrewardcampaign.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rankingrewardcampaign.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rankingrewardcampaign.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TopN(); ok {
		_spec.SetField(rankingrewardcampaign.FieldTopN, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTopN(); ok {
		_spec.AddField(rankingrewardcampaign.FieldTopN, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChanceCount(); ok {
		_spec.SetField(rankingrewardcampaign.FieldChanceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChanceCount(); ok {
		_spec.AddField(rankingrewardcampaign.FieldChanceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PublicDisplayLimit(); ok {
		_spec.SetField(rankingrewardcampaign.FieldPublicDisplayLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPublicDisplayLimit(); ok {
		_spec.AddField(rankingrewardcampaign.FieldPublicDisplayLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinActualCost(); ok {
		_spec.SetField(rankingrewardcampaign.FieldMinActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinActualCost(); ok {
		_spec.AddField(rankingrewardcampaign.FieldMinActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(rankingrewardcampaign.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(rankingrewardcampaign.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(rankingrewardcampaign.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(rankingrewardcampaign.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastRunDate(); ok {
		_spec.SetField(rankingrewardcampaign.FieldLastRunDate, field.TypeTime, value)
	}
	if _u.mutation.LastRunDateCleared() {
		_spec.ClearField(rankingrewardcampaign.FieldLastRunDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(rankingrewardcampaign.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(rankingrewardcampaign.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rankingrewardcampaign.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LotteryCampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rankingrewardcampaign.LotteryCampaignTable,
			Columns: []string{rankingrewardcampaign.LotteryCampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LotteryCampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rankingrewardcampaign.LotteryCampaignTable,
			Columns: []string{rankingrewardcampaign.LotteryCampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExcludedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.ExcludedUsersTable,
			Columns: []string{rankingrewardcampaign.ExcludedUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardexcludeduser.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExcludedUsersIDs(); len(nodes) > 0 && !_u.mutation.ExcludedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.ExcludedUsersTable,
			Columns: []string{rankingrewardcampaign.ExcludedUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardexcludeduser.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExcludedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.ExcludedUsersTable,
			Columns: []string{rankingrewardcampaign.ExcludedUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardexcludeduser.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.RunsTable,
			Columns: []string{rankingrewardcampaign.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardrun.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.RunsTable,
			Columns: []string{rankingrewardcampaign.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.RunsTable,
			Columns: []string{rankingrewardcampaign.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.AwardsTable,
			Columns: []string{rankingrewardcampaign.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAwardsIDs(); len(nodes) > 0 && !_u.mutation.AwardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.AwardsTable,
			Columns: []string{rankingrewardcampaign.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AwardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rankingrewardcampaign.AwardsTable,
			Columns: []string{rankingrewardcampaign.AwardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RankingRewardCampaign{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rankingrewardcampaign.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
