// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycampaign"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardaward"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardcampaign"
	"github.com/Wei-Shaw/sub2api/ent/rankingrewardrun"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RankingRewardAwardQuery is the builder for querying RankingRewardAward entities.
type RankingRewardAwardQuery struct {
	config
	ctx                 *QueryContext
	order               []rankingrewardaward.OrderOption
	inters              []Interceptor
	predicates          []predicate.RankingRewardAward
	withRun             *RankingRewardRunQuery
	withCampaign        *RankingRewardCampaignQuery
	withLotteryCampaign *LotteryCampaignQuery
	withUser            *UserQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RankingRewardAwardQuery builder.
func (_q *RankingRewardAwardQuery) Where(ps ...predicate.RankingRewardAward) *RankingRewardAwardQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RankingRewardAwardQuery) Limit(limit int) *RankingRewardAwardQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RankingRewardAwardQuery) Offset(offset int) *RankingRewardAwardQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RankingRewardAwardQuery) Unique(unique bool) *RankingRewardAwardQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RankingRewardAwardQuery) Order(o ...rankingrewardaward.OrderOption) *RankingRewardAwardQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRun chains the current query on the "run" edge.
func (_q *RankingRewardAwardQuery) QueryRun() *RankingRewardRunQuery {
	query := (&RankingRewardRunClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rankingrewardaward.Table, rankingrewardaward.FieldID, selector),
			sqlgraph.To(rankingrewardrun.Table, rankingrewardrun.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rankingrewardaward.RunTable, rankingrewardaward.RunColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCampaign chains the current query on the "campaign" edge.
func (_q *RankingRewardAwardQuery) QueryCampaign() *RankingRewardCampaignQuery {
	query := (&RankingRewardCampaignClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rankingrewardaward.Table, rankingrewardaward.FieldID, selector),
			sqlgraph.To(rankingrewardcampaign.Table, rankingrewardcampaign.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rankingrewardaward.CampaignTable, rankingrewardaward.CampaignColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLotteryCampaign chains the current query on the "lottery_campaign" edge.
func (_q *RankingRewardAwardQuery) QueryLotteryCampaign() *LotteryCampaignQuery {
	query := (&LotteryCampaignClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rankingrewardaward.Table, rankingrewardaward.FieldID, selector),
			sqlgraph.To(lotterycampaign.Table, lotterycampaign.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rankingrewardaward.LotteryCampaignTable, rankingrewardaward.LotteryCampaignColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *RankingRewardAwardQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rankingrewardaward.Table, rankingrewardaward.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rankingrewardaward.UserTable, rankingrewardaward.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RankingRewardAward entity from the query.
// Returns a *NotFoundError when no RankingRewardAward was found.
func (_q *RankingRewardAwardQuery) First(ctx context.Context) (*RankingRewardAward, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rankingrewardaward.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RankingRewardAwardQuery) FirstX(ctx context.Context) *RankingRewardAward {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RankingRewardAward ID from the query.
// Returns a *NotFoundError when no RankingRewardAward ID was found.
func (_q *RankingRewardAwardQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rankingrewardaward.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RankingRewardAwardQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RankingRewardAward entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RankingRewardAward entity is found.
// Returns a *NotFoundError when no RankingRewardAward entities are found.
func (_q *RankingRewardAwardQuery) Only(ctx context.Context) (*RankingRewardAward, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rankingrewardaward.Label}
	default:
		return nil, &NotSingularError{rankingrewardaward.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RankingRewardAwardQuery) OnlyX(ctx context.Context) *RankingRewardAward {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RankingRewardAward ID in the query.
// Returns a *NotSingularError when more than one RankingRewardAward ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RankingRewardAwardQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rankingrewardaward.Label}
	default:
		err = &NotSingularError{rankingrewardaward.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RankingRewardAwardQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RankingRewardAwards.
func (_q *RankingRewardAwardQuery) All(ctx context.Context) ([]*RankingRewardAward, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RankingRewardAward, *RankingRewardAwardQuery]()
	return withInterceptors[[]*RankingRewardAward](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RankingRewardAwardQuery) AllX(ctx context.Context) []*RankingRewardAward {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RankingRewardAward IDs.
func (_q *RankingRewardAwardQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(rankingrewardaward.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RankingRewardAwardQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RankingRewardAwardQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RankingRewardAwardQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RankingRewardAwardQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RankingRewardAwardQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RankingRewardAwardQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RankingRewardAwardQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RankingRewardAwardQuery) Clone() *RankingRewardAwardQuery {
	if _q == nil {
		return nil
	}
	return &RankingRewardAwardQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]rankingrewardaward.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.RankingRewardAward{}, _q.predicates...),
		withRun:             _q.withRun.Clone(),
		withCampaign:        _q.withCampaign.Clone(),
		withLotteryCampaign: _q.withLotteryCampaign.Clone(),
		withUser:            _q.withUser.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRun tells the query-builder to eager-load the nodes that are connected to
// the "run" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RankingRewardAwardQuery) WithRun(opts ...func(*RankingRewardRunQuery)) *RankingRewardAwardQuery {
	query := (&RankingRewardRunClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRun = query
	return _q
}

// WithCampaign tells the query-builder to eager-load the nodes that are connected to
// the "campaign" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RankingRewardAwardQuery) WithCampaign(opts ...func(*RankingRewardCampaignQuery)) *RankingRewardAwardQuery {
	query := (&RankingRewardCampaignClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCampaign = query
	return _q
}

// WithLotteryCampaign tells the query-builder to eager-load the nodes that are connected to
// the "lottery_campaign" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RankingRewardAwardQuery) WithLotteryCampaign(opts ...func(*LotteryCampaignQuery)) *RankingRewardAwardQuery {
	query := (&LotteryCampaignClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLotteryCampaign = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RankingRewardAwardQuery) WithUser(opts ...func(*UserQuery)) *RankingRewardAwardQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RunID int64 `json:"run_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RankingRewardAward.Query().
//		GroupBy(rankingrewardaward.FieldRunID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RankingRewardAwardQuery) GroupBy(field string, fields ...string) *RankingRewardAwardGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RankingRewardAwardGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = rankingrewardaward.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RunID int64 `json:"run_id,omitempty"`
//	}
//
//	client.RankingRewardAward.Query().
//		Select(rankingrewardaward.FieldRunID).
//		Scan(ctx, &v)
func (_q *RankingRewardAwardQuery) Select(fields ...string) *RankingRewardAwardSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RankingRewardAwardSelect{RankingRewardAwardQuery: _q}
	sbuild.label = rankingrewardaward.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RankingRewardAwardSelect configured with the given aggregations.
func (_q *RankingRewardAwardQuery) Aggregate(fns ...AggregateFunc) *RankingRewardAwardSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RankingRewardAwardQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !rankingrewardaward.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RankingRewardAwardQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RankingRewardAward, error) {
	var (
		nodes       = []*RankingRewardAward{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withRun != nil,
			_q.withCampaign != nil,
			_q.withLotteryCampaign != nil,
			_q.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RankingRewardAward).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RankingRewardAward{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRun; query != nil {
		if err := _q.loadRun(ctx, query, nodes, nil,
			func(n *RankingRewardAward, e *RankingRewardRun) { n.Edges.Run = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCampaign; query != nil {
		if err := _q.loadCampaign(ctx, query, nodes, nil,
			func(n *RankingRewardAward, e *RankingRewardCampaign) { n.Edges.Campaign = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLotteryCampaign; query != nil {
		if err := _q.loadLotteryCampaign(ctx, query, nodes, nil,
			func(n *RankingRewardAward, e *LotteryCampaign) { n.Edges.LotteryCampaign = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *RankingRewardAward, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RankingRewardAwardQuery) loadRun(ctx context.Context, query *RankingRewardRunQuery, nodes []*RankingRewardAward, init func(*RankingRewardAward), assign func(*RankingRewardAward, *RankingRewardRun)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RankingRewardAward)
	for i := range nodes {
		fk := nodes[i].RunID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rankingrewardrun.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "run_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RankingRewardAwardQuery) loadCampaign(ctx context.Context, query *RankingRewardCampaignQuery, nodes []*RankingRewardAward, init func(*RankingRewardAward), assign func(*RankingRewardAward, *RankingRewardCampaign)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RankingRewardAward)
	for i := range nodes {
		fk := nodes[i].CampaignID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rankingrewardcampaign.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "campaign_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RankingRewardAwardQuery) loadLotteryCampaign(ctx context.Context, query *LotteryCampaignQuery, nodes []*RankingRewardAward, init func(*RankingRewardAward), assign func(*RankingRewardAward, *LotteryCampaign)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RankingRewardAward)
	for i := range nodes {
		fk := nodes[i].LotteryCampaignID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(lotterycampaign.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "lottery_campaign_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RankingRewardAwardQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*RankingRewardAward, init func(*RankingRewardAward), assign func(*RankingRewardAward, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RankingRewardAward)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RankingRewardAwardQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RankingRewardAwardQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rankingrewardaward.Table, rankingrewardaward.Columns, sqlgraph.NewFieldSpec(rankingrewardaward.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rankingrewardaward.FieldID)
		for i := range fields {
			if fields[i] != rankingrewardaward.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRun != nil {
			_spec.Node.AddColumnOnce(rankingrewardaward.FieldRunID)
		}
		if _q.withCampaign != nil {
			_spec.Node.AddColumnOnce(rankingrewardaward.FieldCampaignID)
		}
		if _q.withLotteryCampaign != nil {
			_spec.Node.AddColumnOnce(rankingrewardaward.FieldLotteryCampaignID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(rankingrewardaward.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RankingRewardAwardQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(rankingrewardaward.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = rankingrewardaward.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RankingRewardAwardQuery) ForUpdate(opts ...sql.LockOption) *RankingRewardAwardQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RankingRewardAwardQuery) ForShare(opts ...sql.LockOption) *RankingRewardAwardQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// RankingRewardAwardGroupBy is the group-by builder for RankingRewardAward entities.
type RankingRewardAwardGroupBy struct {
	selector
	build *RankingRewardAwardQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RankingRewardAwardGroupBy) Aggregate(fns ...AggregateFunc) *RankingRewardAwardGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RankingRewardAwardGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RankingRewardAwardQuery, *RankingRewardAwardGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RankingRewardAwardGroupBy) sqlScan(ctx context.Context, root *RankingRewardAwardQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RankingRewardAwardSelect is the builder for selecting fields of RankingRewardAward entities.
type RankingRewardAwardSelect struct {
	*RankingRewardAwardQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RankingRewardAwardSelect) Aggregate(fns ...AggregateFunc) *RankingRewardAwardSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RankingRewardAwardSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RankingRewardAwardQuery, *RankingRewardAwardSelect](ctx, _s.RankingRewardAwardQuery, _s, _s.inters, v)
}

func (_s *RankingRewardAwardSelect) sqlScan(ctx context.Context, root *RankingRewardAwardQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
