// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargeresetcampaign"
	"github.com/Wei-Shaw/sub2api/ent/rechargeresetcampaignrule"
	"github.com/Wei-Shaw/sub2api/ent/rechargeresetrecord"
)

// RechargeResetCampaignUpdate is the builder for updating RechargeResetCampaign entities.
type RechargeResetCampaignUpdate struct {
	config
	hooks    []Hook
	mutation *RechargeResetCampaignMutation
}

// Where appends a list predicates to the RechargeResetCampaignUpdate builder.
func (_u *RechargeResetCampaignUpdate) Where(ps ...predicate.RechargeResetCampaign) *RechargeResetCampaignUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RechargeResetCampaignUpdate) SetName(v string) *RechargeResetCampaignUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdate) SetNillableName(v *string) *RechargeResetCampaignUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RechargeResetCampaignUpdate) SetDescription(v string) *RechargeResetCampaignUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdate) SetNillableDescription(v *string) *RechargeResetCampaignUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RechargeResetCampaignUpdate) SetStatus(v string) *RechargeResetCampaignUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdate) SetNillableStatus(v *string) *RechargeResetCampaignUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *RechargeResetCampaignUpdate) SetStartsAt(v time.Time) *RechargeResetCampaignUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdate) SetNillableStartsAt(v *time.Time) *RechargeResetCampaignUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *RechargeResetCampaignUpdate) SetEndsAt(v time.Time) *RechargeResetCampaignUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdate) SetNillableEndsAt(v *time.Time) *RechargeResetCampaignUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *RechargeResetCampaignUpdate) ClearEndsAt() *RechargeResetCampaignUpdate {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetResetDaily sets the "reset_daily" field.
func (_u *RechargeResetCampaignUpdate) SetResetDaily(v bool) *RechargeResetCampaignUpdate {
	_u.mutation.SetResetDaily(v)
	return _u
}

// SetNillableResetDaily sets the "reset_daily" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdate) SetNillableResetDaily(v *bool) *RechargeResetCampaignUpdate {
	if v != nil {
		_u.SetResetDaily(*v)
	}
	return _u
}

// SetResetWeekly sets the "reset_weekly" field.
func (_u *RechargeResetCampaignUpdate) SetResetWeekly(v bool) *RechargeResetCampaignUpdate {
	_u.mutation.SetResetWeekly(v)
	return _u
}

// SetNillableResetWeekly sets the "reset_weekly" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdate) SetNillableResetWeekly(v *bool) *RechargeResetCampaignUpdate {
	if v != nil {
		_u.SetResetWeekly(*v)
	}
	return _u
}

// SetResetMonthly sets the "reset_monthly" field.
func (_u *RechargeResetCampaignUpdate) SetResetMonthly(v bool) *RechargeResetCampaignUpdate {
	_u.mutation.SetResetMonthly(v)
	return _u
}

// SetNillableResetMonthly sets the "reset_monthly" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdate) SetNillableResetMonthly(v *bool) *RechargeResetCampaignUpdate {
	if v != nil {
		_u.SetResetMonthly(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RechargeResetCampaignUpdate) SetMetadata(v map[string]interface{}) *RechargeResetCampaignUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RechargeResetCampaignUpdate) ClearMetadata() *RechargeResetCampaignUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargeResetCampaignUpdate) SetUpdatedAt(v time.Time) *RechargeResetCampaignUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRuleIDs adds the "rules" edge to the RechargeResetCampaignRule entity by IDs.
func (_u *RechargeResetCampaignUpdate) AddRuleIDs(ids ...int64) *RechargeResetCampaignUpdate {
	_u.mutation.AddRuleIDs(ids...)
	return _u
}

// AddRules adds the "rules" edges to the RechargeResetCampaignRule entity.
func (_u *RechargeResetCampaignUpdate) AddRules(v ...*RechargeResetCampaignRule) *RechargeResetCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRuleIDs(ids...)
}

// AddRecordIDs adds the "records" edge to the RechargeResetRecord entity by IDs.
func (_u *RechargeResetCampaignUpdate) AddRecordIDs(ids ...int64) *RechargeResetCampaignUpdate {
	_u.mutation.AddRecordIDs(ids...)
	return _u
}

// AddRecords adds the "records" edges to the RechargeResetRecord entity.
func (_u *RechargeResetCampaignUpdate) AddRecords(v ...*RechargeResetRecord) *RechargeResetCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordIDs(ids...)
}

// Mutation returns the RechargeResetCampaignMutation object of the builder.
func (_u *RechargeResetCampaignUpdate) Mutation() *RechargeResetCampaignMutation {
	return _u.mutation
}

// ClearRules clears all "rules" edges to the RechargeResetCampaignRule entity.
func (_u *RechargeResetCampaignUpdate) ClearRules() *RechargeResetCampaignUpdate {
	_u.mutation.ClearRules()
	return _u
}

// RemoveRuleIDs removes the "rules" edge to RechargeResetCampaignRule entities by IDs.
func (_u *RechargeResetCampaignUpdate) RemoveRuleIDs(ids ...int64) *RechargeResetCampaignUpdate {
	_u.mutation.RemoveRuleIDs(ids...)
	return _u
}

// RemoveRules removes "rules" edges to RechargeResetCampaignRule entities.
func (_u *RechargeResetCampaignUpdate) RemoveRules(v ...*RechargeResetCampaignRule) *RechargeResetCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRuleIDs(ids...)
}

// ClearRecords clears all "records" edges to the RechargeResetRecord entity.
func (_u *RechargeResetCampaignUpdate) ClearRecords() *RechargeResetCampaignUpdate {
	_u.mutation.ClearRecords()
	return _u
}

// RemoveRecordIDs removes the "records" edge to RechargeResetRecord entities by IDs.
func (_u *RechargeResetCampaignUpdate) RemoveRecordIDs(ids ...int64) *RechargeResetCampaignUpdate {
	_u.mutation.RemoveRecordIDs(ids...)
	return _u
}

// RemoveRecords removes "records" edges to RechargeResetRecord entities.
func (_u *RechargeResetCampaignUpdate) RemoveRecords(v ...*RechargeResetRecord) *RechargeResetCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RechargeResetCampaignUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeResetCampaignUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RechargeResetCampaignUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeResetCampaignUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RechargeResetCampaignUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rechargeresetcampaign.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeResetCampaignUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rechargeresetcampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RechargeResetCampaign.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rechargeresetcampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeResetCampaign.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RechargeResetCampaignUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargeresetcampaign.Table, rechargeresetcampaign.Columns, sqlgraph.NewFieldSpec(rechargeresetcampaign.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rechargeresetcampaign.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rechargeresetcampaign.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rechargeresetcampaign.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(rechargeresetcampaign.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(rechargeresetcampaign.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(rechargeresetcampaign.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResetDaily(); ok {
		_spec.SetField(rechargeresetcampaign.FieldResetDaily, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResetWeekly(); ok {
		_spec.SetField(rechargeresetcampaign.FieldResetWeekly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResetMonthly(); ok {
		_spec.SetField(rechargeresetcampaign.FieldResetMonthly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(rechargeresetcampaign.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(rechargeresetcampaign.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeresetcampaign.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RulesTable,
			Columns: []string{rechargeresetcampaign.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetcampaignrule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRulesIDs(); len(nodes) > 0 && !_u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RulesTable,
			Columns: []string{rechargeresetcampaign.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetcampaignrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RulesTable,
			Columns: []string{rechargeresetcampaign.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetcampaignrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RecordsTable,
			Columns: []string{rechargeresetcampaign.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !_u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RecordsTable,
			Columns: []string{rechargeresetcampaign.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RecordsTable,
			Columns: []string{rechargeresetcampaign.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargeresetcampaign.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RechargeResetCampaignUpdateOne is the builder for updating a single RechargeResetCampaign entity.
type RechargeResetCampaignUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RechargeResetCampaignMutation
}

// SetName sets the "name" field.
func (_u *RechargeResetCampaignUpdateOne) SetName(v string) *RechargeResetCampaignUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdateOne) SetNillableName(v *string) *RechargeResetCampaignUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RechargeResetCampaignUpdateOne) SetDescription(v string) *RechargeResetCampaignUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdateOne) SetNillableDescription(v *string) *RechargeResetCampaignUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RechargeResetCampaignUpdateOne) SetStatus(v string) *RechargeResetCampaignUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdateOne) SetNillableStatus(v *string) *RechargeResetCampaignUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *RechargeResetCampaignUpdateOne) SetStartsAt(v time.Time) *RechargeResetCampaignUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdateOne) SetNillableStartsAt(v *time.Time) *RechargeResetCampaignUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *RechargeResetCampaignUpdateOne) SetEndsAt(v time.Time) *RechargeResetCampaignUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdateOne) SetNillableEndsAt(v *time.Time) *RechargeResetCampaignUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *RechargeResetCampaignUpdateOne) ClearEndsAt() *RechargeResetCampaignUpdateOne {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetResetDaily sets the "reset_daily" field.
func (_u *RechargeResetCampaignUpdateOne) SetResetDaily(v bool) *RechargeResetCampaignUpdateOne {
	_u.mutation.SetResetDaily(v)
	return _u
}

// SetNillableResetDaily sets the "reset_daily" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdateOne) SetNillableResetDaily(v *bool) *RechargeResetCampaignUpdateOne {
	if v != nil {
		_u.SetResetDaily(*v)
	}
	return _u
}

// SetResetWeekly sets the "reset_weekly" field.
func (_u *RechargeResetCampaignUpdateOne) SetResetWeekly(v bool) *RechargeResetCampaignUpdateOne {
	_u.mutation.SetResetWeekly(v)
	return _u
}

// SetNillableResetWeekly sets the "reset_weekly" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdateOne) SetNillableResetWeekly(v *bool) *RechargeResetCampaignUpdateOne {
	if v != nil {
		_u.SetResetWeekly(*v)
	}
	return _u
}

// SetResetMonthly sets the "reset_monthly" field.
func (_u *RechargeResetCampaignUpdateOne) SetResetMonthly(v bool) *RechargeResetCampaignUpdateOne {
	_u.mutation.SetResetMonthly(v)
	return _u
}

// SetNillableResetMonthly sets the "reset_monthly" field if the given value is not nil.
func (_u *RechargeResetCampaignUpdateOne) SetNillableResetMonthly(v *bool) *RechargeResetCampaignUpdateOne {
	if v != nil {
		_u.SetResetMonthly(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RechargeResetCampaignUpdateOne) SetMetadata(v map[string]interface{}) *RechargeResetCampaignUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RechargeResetCampaignUpdateOne) ClearMetadata() *RechargeResetCampaignUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargeResetCampaignUpdateOne) SetUpdatedAt(v time.Time) *RechargeResetCampaignUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRuleIDs adds the "rules" edge to the RechargeResetCampaignRule entity by IDs.
func (_u *RechargeResetCampaignUpdateOne) AddRuleIDs(ids ...int64) *RechargeResetCampaignUpdateOne {
	_u.mutation.AddRuleIDs(ids...)
	return _u
}

// AddRules adds the "rules" edges to the RechargeResetCampaignRule entity.
func (_u *RechargeResetCampaignUpdateOne) AddRules(v ...*RechargeResetCampaignRule) *RechargeResetCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRuleIDs(ids...)
}

// AddRecordIDs adds the "records" edge to the RechargeResetRecord entity by IDs.
func (_u *RechargeResetCampaignUpdateOne) AddRecordIDs(ids ...int64) *RechargeResetCampaignUpdateOne {
	_u.mutation.AddRecordIDs(ids...)
	return _u
}

// AddRecords adds the "records" edges to the RechargeResetRecord entity.
func (_u *RechargeResetCampaignUpdateOne) AddRecords(v ...*RechargeResetRecord) *RechargeResetCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordIDs(ids...)
}

// Mutation returns the RechargeResetCampaignMutation object of the builder.
func (_u *RechargeResetCampaignUpdateOne) Mutation() *RechargeResetCampaignMutation {
	return _u.mutation
}

// ClearRules clears all "rules" edges to the RechargeResetCampaignRule entity.
func (_u *RechargeResetCampaignUpdateOne) ClearRules() *RechargeResetCampaignUpdateOne {
	_u.mutation.ClearRules()
	return _u
}

// RemoveRuleIDs removes the "rules" edge to RechargeResetCampaignRule entities by IDs.
func (_u *RechargeResetCampaignUpdateOne) RemoveRuleIDs(ids ...int64) *RechargeResetCampaignUpdateOne {
	_u.mutation.RemoveRuleIDs(ids...)
	return _u
}

// RemoveRules removes "rules" edges to RechargeResetCampaignRule entities.
func (_u *RechargeResetCampaignUpdateOne) RemoveRules(v ...*RechargeResetCampaignRule) *RechargeResetCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRuleIDs(ids...)
}

// ClearRecords clears all "records" edges to the RechargeResetRecord entity.
func (_u *RechargeResetCampaignUpdateOne) ClearRecords() *RechargeResetCampaignUpdateOne {
	_u.mutation.ClearRecords()
	return _u
}

// RemoveRecordIDs removes the "records" edge to RechargeResetRecord entities by IDs.
func (_u *RechargeResetCampaignUpdateOne) RemoveRecordIDs(ids ...int64) *RechargeResetCampaignUpdateOne {
	_u.mutation.RemoveRecordIDs(ids...)
	return _u
}

// RemoveRecords removes "records" edges to RechargeResetRecord entities.
func (_u *RechargeResetCampaignUpdateOne) RemoveRecords(v ...*RechargeResetRecord) *RechargeResetCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordIDs(ids...)
}

// Where appends a list predicates to the RechargeResetCampaignUpdate builder.
func (_u *RechargeResetCampaignUpdateOne) Where(ps ...predicate.RechargeResetCampaign) *RechargeResetCampaignUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RechargeResetCampaignUpdateOne) Select(field string, fields ...string) *RechargeResetCampaignUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RechargeResetCampaign entity.
func (_u *RechargeResetCampaignUpdateOne) Save(ctx context.Context) (*RechargeResetCampaign, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeResetCampaignUpdateOne) SaveX(ctx context.Context) *RechargeResetCampaign {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RechargeResetCampaignUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeResetCampaignUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RechargeResetCampaignUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rechargeresetcampaign.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeResetCampaignUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rechargeresetcampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RechargeResetCampaign.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rechargeresetcampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeResetCampaign.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RechargeResetCampaignUpdateOne) sqlSave(ctx context.Context) (_node *RechargeResetCampaign, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargeresetcampaign.Table, rechargeresetcampaign.Columns, sqlgraph.NewFieldSpec(rechargeresetcampaign.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RechargeResetCampaign.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rechargeresetcampaign.FieldID)
		for _, f := range fields {
			if !rechargeresetcampaign.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rechargeresetcampaign.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rechargeresetcampaign.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rechargeresetcampaign.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rechargeresetcampaign.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(rechargeresetcampaign.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(rechargeresetcampaign.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(rechargeresetcampaign.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResetDaily(); ok {
		_spec.SetField(rechargeresetcampaign.FieldResetDaily, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResetWeekly(); ok {
		_spec.SetField(rechargeresetcampaign.FieldResetWeekly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResetMonthly(); ok {
		_spec.SetField(rechargeresetcampaign.FieldResetMonthly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(rechargeresetcampaign.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(rechargeresetcampaign.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeresetcampaign.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RulesTable,
			Columns: []string{rechargeresetcampaign.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetcampaignrule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRulesIDs(); len(nodes) > 0 && !_u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RulesTable,
			Columns: []string{rechargeresetcampaign.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetcampaignrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RulesTable,
			Columns: []string{rechargeresetcampaign.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetcampaignrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RecordsTable,
			Columns: []string{rechargeresetcampaign.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !_u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RecordsTable,
			Columns: []string{rechargeresetcampaign.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeresetcampaign.RecordsTable,
			Columns: []string{rechargeresetcampaign.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeresetrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RechargeResetCampaign{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargeresetcampaign.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
