// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/rechargeresetcampaign"
	"github.com/Wei-Shaw/sub2api/ent/rechargeresetcampaignrule"
	"github.com/Wei-Shaw/sub2api/ent/rechargeresetrecord"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// RechargeResetRecord is the model entity for the RechargeResetRecord schema.
type RechargeResetRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CampaignID holds the value of the "campaign_id" field.
	CampaignID int64 `json:"campaign_id,omitempty"`
	// RuleID holds the value of the "rule_id" field.
	RuleID int64 `json:"rule_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// RechargeAmount holds the value of the "recharge_amount" field.
	RechargeAmount float64 `json:"recharge_amount,omitempty"`
	// ThresholdAmount holds the value of the "threshold_amount" field.
	ThresholdAmount float64 `json:"threshold_amount,omitempty"`
	// ResetDaily holds the value of the "reset_daily" field.
	ResetDaily bool `json:"reset_daily,omitempty"`
	// ResetWeekly holds the value of the "reset_weekly" field.
	ResetWeekly bool `json:"reset_weekly,omitempty"`
	// ResetMonthly holds the value of the "reset_monthly" field.
	ResetMonthly bool `json:"reset_monthly,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RechargeResetRecordQuery when eager-loading is set.
	Edges        RechargeResetRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RechargeResetRecordEdges holds the relations/edges for other nodes in the graph.
type RechargeResetRecordEdges struct {
	// Campaign holds the value of the campaign edge.
	Campaign *RechargeResetCampaign `json:"campaign,omitempty"`
	// Rule holds the value of the rule edge.
	Rule *RechargeResetCampaignRule `json:"rule,omitempty"`
	// Order holds the value of the order edge.
	Order *PaymentOrder `json:"order,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// CampaignOrErr returns the Campaign value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeResetRecordEdges) CampaignOrErr() (*RechargeResetCampaign, error) {
	if e.Campaign != nil {
		return e.Campaign, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: rechargeresetcampaign.Label}
	}
	return nil, &NotLoadedError{edge: "campaign"}
}

// RuleOrErr returns the Rule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeResetRecordEdges) RuleOrErr() (*RechargeResetCampaignRule, error) {
	if e.Rule != nil {
		return e.Rule, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: rechargeresetcampaignrule.Label}
	}
	return nil, &NotLoadedError{edge: "rule"}
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeResetRecordEdges) OrderOrErr() (*PaymentOrder, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeResetRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeResetRecordEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeResetRecordEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RechargeResetRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rechargeresetrecord.FieldMetadata:
			values[i] = new([]byte)
		case rechargeresetrecord.FieldResetDaily, rechargeresetrecord.FieldResetWeekly, rechargeresetrecord.FieldResetMonthly:
			values[i] = new(sql.NullBool)
		case rechargeresetrecord.FieldRechargeAmount, rechargeresetrecord.FieldThresholdAmount:
			values[i] = new(sql.NullFloat64)
		case rechargeresetrecord.FieldID, rechargeresetrecord.FieldCampaignID, rechargeresetrecord.FieldRuleID, rechargeresetrecord.FieldOrderID, rechargeresetrecord.FieldUserID, rechargeresetrecord.FieldSubscriptionID, rechargeresetrecord.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case rechargeresetrecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RechargeResetRecord fields.
func (_m *RechargeResetRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rechargeresetrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rechargeresetrecord.FieldCampaignID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field campaign_id", values[i])
			} else if value.Valid {
				_m.CampaignID = value.Int64
			}
		case rechargeresetrecord.FieldRuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				_m.RuleID = value.Int64
			}
		case rechargeresetrecord.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case rechargeresetrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case rechargeresetrecord.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case rechargeresetrecord.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case rechargeresetrecord.FieldRechargeAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field recharge_amount", values[i])
			} else if value.Valid {
				_m.RechargeAmount = value.Float64
			}
		case rechargeresetrecord.FieldThresholdAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field threshold_amount", values[i])
			} else if value.Valid {
				_m.ThresholdAmount = value.Float64
			}
		case rechargeresetrecord.FieldResetDaily:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field reset_daily", values[i])
			} else if value.Valid {
				_m.ResetDaily = value.Bool
			}
		case rechargeresetrecord.FieldResetWeekly:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field reset_weekly", values[i])
			} else if value.Valid {
				_m.ResetWeekly = value.Bool
			}
		case rechargeresetrecord.FieldResetMonthly:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field reset_monthly", values[i])
			} else if value.Valid {
				_m.ResetMonthly = value.Bool
			}
		case rechargeresetrecord.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case rechargeresetrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RechargeResetRecord.
// This includes values selected through modifiers, order, etc.
func (_m *RechargeResetRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCampaign queries the "campaign" edge of the RechargeResetRecord entity.
func (_m *RechargeResetRecord) QueryCampaign() *RechargeResetCampaignQuery {
	return NewRechargeResetRecordClient(_m.config).QueryCampaign(_m)
}

// QueryRule queries the "rule" edge of the RechargeResetRecord entity.
func (_m *RechargeResetRecord) QueryRule() *RechargeResetCampaignRuleQuery {
	return NewRechargeResetRecordClient(_m.config).QueryRule(_m)
}

// QueryOrder queries the "order" edge of the RechargeResetRecord entity.
func (_m *RechargeResetRecord) QueryOrder() *PaymentOrderQuery {
	return NewRechargeResetRecordClient(_m.config).QueryOrder(_m)
}

// QueryUser queries the "user" edge of the RechargeResetRecord entity.
func (_m *RechargeResetRecord) QueryUser() *UserQuery {
	return NewRechargeResetRecordClient(_m.config).QueryUser(_m)
}

// QuerySubscription queries the "subscription" edge of the RechargeResetRecord entity.
func (_m *RechargeResetRecord) QuerySubscription() *UserSubscriptionQuery {
	return NewRechargeResetRecordClient(_m.config).QuerySubscription(_m)
}

// QueryGroup queries the "group" edge of the RechargeResetRecord entity.
func (_m *RechargeResetRecord) QueryGroup() *GroupQuery {
	return NewRechargeResetRecordClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this RechargeResetRecord.
// Note that you need to call RechargeResetRecord.Unwrap() before calling this method if this RechargeResetRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RechargeResetRecord) Update() *RechargeResetRecordUpdateOne {
	return NewRechargeResetRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RechargeResetRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RechargeResetRecord) Unwrap() *RechargeResetRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RechargeResetRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RechargeResetRecord) String() string {
	var builder strings.Builder
	builder.WriteString("RechargeResetRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("campaign_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CampaignID))
	builder.WriteString(", ")
	builder.WriteString("rule_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RuleID))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("recharge_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RechargeAmount))
	builder.WriteString(", ")
	builder.WriteString("threshold_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThresholdAmount))
	builder.WriteString(", ")
	builder.WriteString("reset_daily=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResetDaily))
	builder.WriteString(", ")
	builder.WriteString("reset_weekly=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResetWeekly))
	builder.WriteString(", ")
	builder.WriteString("reset_monthly=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResetMonthly))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RechargeResetRecords is a parsable slice of RechargeResetRecord.
type RechargeResetRecords []*RechargeResetRecord
