// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userquotagrant"
)

// UserQuotaGrant is the model entity for the UserQuotaGrant schema.
type UserQuotaGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AmountUsd holds the value of the "amount_usd" field.
	AmountUsd float64 `json:"amount_usd,omitempty"`
	// UsedAmountUsd holds the value of the "used_amount_usd" field.
	UsedAmountUsd float64 `json:"used_amount_usd,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID string `json:"source_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuotaGrantQuery when eager-loading is set.
	Edges        UserQuotaGrantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserQuotaGrantEdges holds the relations/edges for other nodes in the graph.
type UserQuotaGrantEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserQuotaGrantEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserQuotaGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userquotagrant.FieldMetadata:
			values[i] = new([]byte)
		case userquotagrant.FieldAmountUsd, userquotagrant.FieldUsedAmountUsd:
			values[i] = new(sql.NullFloat64)
		case userquotagrant.FieldID, userquotagrant.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userquotagrant.FieldSource, userquotagrant.FieldSourceID, userquotagrant.FieldStatus:
			values[i] = new(sql.NullString)
		case userquotagrant.FieldStartsAt, userquotagrant.FieldExpiresAt, userquotagrant.FieldCreatedAt, userquotagrant.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserQuotaGrant fields.
func (_m *UserQuotaGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userquotagrant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userquotagrant.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userquotagrant.FieldAmountUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_usd", values[i])
			} else if value.Valid {
				_m.AmountUsd = value.Float64
			}
		case userquotagrant.FieldUsedAmountUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field used_amount_usd", values[i])
			} else if value.Valid {
				_m.UsedAmountUsd = value.Float64
			}
		case userquotagrant.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case userquotagrant.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case userquotagrant.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case userquotagrant.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.String
			}
		case userquotagrant.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case userquotagrant.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case userquotagrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userquotagrant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserQuotaGrant.
// This includes values selected through modifiers, order, etc.
func (_m *UserQuotaGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserQuotaGrant entity.
func (_m *UserQuotaGrant) QueryUser() *UserQuery {
	return NewUserQuotaGrantClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserQuotaGrant.
// Note that you need to call UserQuotaGrant.Unwrap() before calling this method if this UserQuotaGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserQuotaGrant) Update() *UserQuotaGrantUpdateOne {
	return NewUserQuotaGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserQuotaGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserQuotaGrant) Unwrap() *UserQuotaGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserQuotaGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserQuotaGrant) String() string {
	var builder strings.Builder
	builder.WriteString("UserQuotaGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountUsd))
	builder.WriteString(", ")
	builder.WriteString("used_amount_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedAmountUsd))
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(_m.SourceID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserQuotaGrants is a parsable slice of UserQuotaGrant.
type UserQuotaGrants []*UserQuotaGrant
