// Code generated by ent, DO NOT EDIT.

package rechargeresetcampaign

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldStatus, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldStartsAt, v))
}

// EndsAt applies equality check predicate on the "ends_at" field. It's identical to EndsAtEQ.
func EndsAt(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldEndsAt, v))
}

// ResetDaily applies equality check predicate on the "reset_daily" field. It's identical to ResetDailyEQ.
func ResetDaily(v bool) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldResetDaily, v))
}

// ResetWeekly applies equality check predicate on the "reset_weekly" field. It's identical to ResetWeeklyEQ.
func ResetWeekly(v bool) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldResetWeekly, v))
}

// ResetMonthly applies equality check predicate on the "reset_monthly" field. It's identical to ResetMonthlyEQ.
func ResetMonthly(v bool) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldResetMonthly, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldContainsFold(FieldStatus, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLTE(FieldStartsAt, v))
}

// EndsAtEQ applies the EQ predicate on the "ends_at" field.
func EndsAtEQ(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldEndsAt, v))
}

// EndsAtNEQ applies the NEQ predicate on the "ends_at" field.
func EndsAtNEQ(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldEndsAt, v))
}

// EndsAtIn applies the In predicate on the "ends_at" field.
func EndsAtIn(vs ...time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldIn(FieldEndsAt, vs...))
}

// EndsAtNotIn applies the NotIn predicate on the "ends_at" field.
func EndsAtNotIn(vs ...time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNotIn(FieldEndsAt, vs...))
}

// EndsAtGT applies the GT predicate on the "ends_at" field.
func EndsAtGT(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGT(FieldEndsAt, v))
}

// EndsAtGTE applies the GTE predicate on the "ends_at" field.
func EndsAtGTE(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGTE(FieldEndsAt, v))
}

// EndsAtLT applies the LT predicate on the "ends_at" field.
func EndsAtLT(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLT(FieldEndsAt, v))
}

// EndsAtLTE applies the LTE predicate on the "ends_at" field.
func EndsAtLTE(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLTE(FieldEndsAt, v))
}

// EndsAtIsNil applies the IsNil predicate on the "ends_at" field.
func EndsAtIsNil() predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldIsNull(FieldEndsAt))
}

// EndsAtNotNil applies the NotNil predicate on the "ends_at" field.
func EndsAtNotNil() predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNotNull(FieldEndsAt))
}

// ResetDailyEQ applies the EQ predicate on the "reset_daily" field.
func ResetDailyEQ(v bool) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldResetDaily, v))
}

// ResetDailyNEQ applies the NEQ predicate on the "reset_daily" field.
func ResetDailyNEQ(v bool) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldResetDaily, v))
}

// ResetWeeklyEQ applies the EQ predicate on the "reset_weekly" field.
func ResetWeeklyEQ(v bool) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldResetWeekly, v))
}

// ResetWeeklyNEQ applies the NEQ predicate on the "reset_weekly" field.
func ResetWeeklyNEQ(v bool) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldResetWeekly, v))
}

// ResetMonthlyEQ applies the EQ predicate on the "reset_monthly" field.
func ResetMonthlyEQ(v bool) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldResetMonthly, v))
}

// ResetMonthlyNEQ applies the NEQ predicate on the "reset_monthly" field.
func ResetMonthlyNEQ(v bool) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldResetMonthly, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasRules applies the HasEdge predicate on the "rules" edge.
func HasRules() predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RulesTable, RulesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRulesWith applies the HasEdge predicate on the "rules" edge with a given conditions (other predicates).
func HasRulesWith(preds ...predicate.RechargeResetCampaignRule) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(func(s *sql.Selector) {
		step := newRulesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecords applies the HasEdge predicate on the "records" edge.
func HasRecords() predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecordsTable, RecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecordsWith applies the HasEdge predicate on the "records" edge with a given conditions (other predicates).
func HasRecordsWith(preds ...predicate.RechargeResetRecord) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(func(s *sql.Selector) {
		step := newRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RechargeResetCampaign) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RechargeResetCampaign) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RechargeResetCampaign) predicate.RechargeResetCampaign {
	return predicate.RechargeResetCampaign(sql.NotPredicates(p))
}
