// Code generated by ent, DO NOT EDIT.

package rankingrewardaward

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rankingrewardaward type in the database.
	Label = "ranking_reward_award"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldCampaignID holds the string denoting the campaign_id field in the database.
	FieldCampaignID = "campaign_id"
	// FieldLotteryCampaignID holds the string denoting the lottery_campaign_id field in the database.
	FieldLotteryCampaignID = "lottery_campaign_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRank holds the string denoting the rank field in the database.
	FieldRank = "rank"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldRequests holds the string denoting the requests field in the database.
	FieldRequests = "requests"
	// FieldTokens holds the string denoting the tokens field in the database.
	FieldTokens = "tokens"
	// FieldChanceCount holds the string denoting the chance_count field in the database.
	FieldChanceCount = "chance_count"
	// FieldLotteryChanceIds holds the string denoting the lottery_chance_ids field in the database.
	FieldLotteryChanceIds = "lottery_chance_ids"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeRun holds the string denoting the run edge name in mutations.
	EdgeRun = "run"
	// EdgeCampaign holds the string denoting the campaign edge name in mutations.
	EdgeCampaign = "campaign"
	// EdgeLotteryCampaign holds the string denoting the lottery_campaign edge name in mutations.
	EdgeLotteryCampaign = "lottery_campaign"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the rankingrewardaward in the database.
	Table = "ranking_reward_awards"
	// RunTable is the table that holds the run relation/edge.
	RunTable = "ranking_reward_awards"
	// RunInverseTable is the table name for the RankingRewardRun entity.
	// It exists in this package in order to avoid circular dependency with the "rankingrewardrun" package.
	RunInverseTable = "ranking_reward_runs"
	// RunColumn is the table column denoting the run relation/edge.
	RunColumn = "run_id"
	// CampaignTable is the table that holds the campaign relation/edge.
	CampaignTable = "ranking_reward_awards"
	// CampaignInverseTable is the table name for the RankingRewardCampaign entity.
	// It exists in this package in order to avoid circular dependency with the "rankingrewardcampaign" package.
	CampaignInverseTable = "ranking_reward_campaigns"
	// CampaignColumn is the table column denoting the campaign relation/edge.
	CampaignColumn = "campaign_id"
	// LotteryCampaignTable is the table that holds the lottery_campaign relation/edge.
	LotteryCampaignTable = "ranking_reward_awards"
	// LotteryCampaignInverseTable is the table name for the LotteryCampaign entity.
	// It exists in this package in order to avoid circular dependency with the "lotterycampaign" package.
	LotteryCampaignInverseTable = "lottery_campaigns"
	// LotteryCampaignColumn is the table column denoting the lottery_campaign relation/edge.
	LotteryCampaignColumn = "lottery_campaign_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "ranking_reward_awards"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for rankingrewardaward fields.
var Columns = []string{
	FieldID,
	FieldRunID,
	FieldCampaignID,
	FieldLotteryCampaignID,
	FieldUserID,
	FieldRank,
	FieldActualCost,
	FieldRequests,
	FieldTokens,
	FieldChanceCount,
	FieldLotteryChanceIds,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultActualCost holds the default value on creation for the "actual_cost" field.
	DefaultActualCost float64
	// DefaultRequests holds the default value on creation for the "requests" field.
	DefaultRequests int64
	// DefaultTokens holds the default value on creation for the "tokens" field.
	DefaultTokens int64
	// DefaultChanceCount holds the default value on creation for the "chance_count" field.
	DefaultChanceCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RankingRewardAward queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByCampaignID orders the results by the campaign_id field.
func ByCampaignID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCampaignID, opts...).ToFunc()
}

// ByLotteryCampaignID orders the results by the lottery_campaign_id field.
func ByLotteryCampaignID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLotteryCampaignID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByRank orders the results by the rank field.
func ByRank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRank, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByRequests orders the results by the requests field.
func ByRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequests, opts...).ToFunc()
}

// ByTokens orders the results by the tokens field.
func ByTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokens, opts...).ToFunc()
}

// ByChanceCount orders the results by the chance_count field.
func ByChanceCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChanceCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRunField orders the results by run field.
func ByRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunStep(), sql.OrderByField(field, opts...))
	}
}

// ByCampaignField orders the results by campaign field.
func ByCampaignField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCampaignStep(), sql.OrderByField(field, opts...))
	}
}

// ByLotteryCampaignField orders the results by lottery_campaign field.
func ByLotteryCampaignField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLotteryCampaignStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RunTable, RunColumn),
	)
}
func newCampaignStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CampaignInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CampaignTable, CampaignColumn),
	)
}
func newLotteryCampaignStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LotteryCampaignInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LotteryCampaignTable, LotteryCampaignColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
