// Code generated by ent, DO NOT EDIT.

package lotteryprize

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the lotteryprize type in the database.
	Label = "lottery_prize"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCampaignID holds the string denoting the campaign_id field in the database.
	FieldCampaignID = "campaign_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldStockTotal holds the string denoting the stock_total field in the database.
	FieldStockTotal = "stock_total"
	// FieldStockUsed holds the string denoting the stock_used field in the database.
	FieldStockUsed = "stock_used"
	// FieldRedeemType holds the string denoting the redeem_type field in the database.
	FieldRedeemType = "redeem_type"
	// FieldRedeemValue holds the string denoting the redeem_value field in the database.
	FieldRedeemValue = "redeem_value"
	// FieldRedeemGroupID holds the string denoting the redeem_group_id field in the database.
	FieldRedeemGroupID = "redeem_group_id"
	// FieldRedeemValidityDays holds the string denoting the redeem_validity_days field in the database.
	FieldRedeemValidityDays = "redeem_validity_days"
	// FieldRedeemMetadata holds the string denoting the redeem_metadata field in the database.
	FieldRedeemMetadata = "redeem_metadata"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCampaign holds the string denoting the campaign edge name in mutations.
	EdgeCampaign = "campaign"
	// EdgeDraws holds the string denoting the draws edge name in mutations.
	EdgeDraws = "draws"
	// Table holds the table name of the lotteryprize in the database.
	Table = "lottery_prizes"
	// CampaignTable is the table that holds the campaign relation/edge.
	CampaignTable = "lottery_prizes"
	// CampaignInverseTable is the table name for the LotteryCampaign entity.
	// It exists in this package in order to avoid circular dependency with the "lotterycampaign" package.
	CampaignInverseTable = "lottery_campaigns"
	// CampaignColumn is the table column denoting the campaign relation/edge.
	CampaignColumn = "campaign_id"
	// DrawsTable is the table that holds the draws relation/edge.
	DrawsTable = "lottery_draws"
	// DrawsInverseTable is the table name for the LotteryDraw entity.
	// It exists in this package in order to avoid circular dependency with the "lotterydraw" package.
	DrawsInverseTable = "lottery_draws"
	// DrawsColumn is the table column denoting the draws relation/edge.
	DrawsColumn = "prize_id"
)

// Columns holds all SQL columns for lotteryprize fields.
var Columns = []string{
	FieldID,
	FieldCampaignID,
	FieldName,
	FieldDescription,
	FieldStatus,
	FieldWeight,
	FieldStockTotal,
	FieldStockUsed,
	FieldRedeemType,
	FieldRedeemValue,
	FieldRedeemGroupID,
	FieldRedeemValidityDays,
	FieldRedeemMetadata,
	FieldSortOrder,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
	// DefaultStockTotal holds the default value on creation for the "stock_total" field.
	DefaultStockTotal int
	// DefaultStockUsed holds the default value on creation for the "stock_used" field.
	DefaultStockUsed int
	// RedeemTypeValidator is a validator for the "redeem_type" field. It is called by the builders before save.
	RedeemTypeValidator func(string) error
	// DefaultRedeemValue holds the default value on creation for the "redeem_value" field.
	DefaultRedeemValue float64
	// DefaultRedeemValidityDays holds the default value on creation for the "redeem_validity_days" field.
	DefaultRedeemValidityDays int
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryPrize queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCampaignID orders the results by the campaign_id field.
func ByCampaignID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCampaignID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByStockTotal orders the results by the stock_total field.
func ByStockTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStockTotal, opts...).ToFunc()
}

// ByStockUsed orders the results by the stock_used field.
func ByStockUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStockUsed, opts...).ToFunc()
}

// ByRedeemType orders the results by the redeem_type field.
func ByRedeemType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemType, opts...).ToFunc()
}

// ByRedeemValue orders the results by the redeem_value field.
func ByRedeemValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemValue, opts...).ToFunc()
}

// ByRedeemGroupID orders the results by the redeem_group_id field.
func ByRedeemGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemGroupID, opts...).ToFunc()
}

// ByRedeemValidityDays orders the results by the redeem_validity_days field.
func ByRedeemValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemValidityDays, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCampaignField orders the results by campaign field.
func ByCampaignField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCampaignStep(), sql.OrderByField(field, opts...))
	}
}

// ByDrawsCount orders the results by draws count.
func ByDrawsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDrawsStep(), opts...)
	}
}

// ByDraws orders the results by draws terms.
func ByDraws(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDrawsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCampaignStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CampaignInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CampaignTable, CampaignColumn),
	)
}
func newDrawsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DrawsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DrawsTable, DrawsColumn),
	)
}
